;; *********************************************************************************************************************
;; Test accessing data, parsing json, etc, from espn nfl api
;; *********************************************************************************************************************

(use-modules (oop goops))

(use-modules (web client))
(use-modules (web response))

(use-modules (bad-cat utils))

(use-modules (bad-cat nfldb json))
(use-modules (bad-cat nfldb game))
(use-modules (bad-cat nfldb team))
(use-modules (bad-cat nfldb serialize))
(use-modules (bad-cat nfldb espn))
(use-modules (bad-cat nfldb data))

;; https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events
; (define espn-host-core "sports.core.api.espn.com")
; (define espn-host-cdn "cdn.espn.com")

(define events-path "v2/sports/football/leagues/nfl/events")

(define div-map (make-hash-table))
(define conf-map (make-hash-table))
(define url-map (make-hash-table))

;;
;; Manage mappings to conferences and divisions
;;

(define (lookup-conf-id id)
  (let ( (conf-sym (hash-ref conf-map id)) )
    (if conf-sym
      conf-sym
      (let ( (page (format #f "v2/sports/football/leagues/nfl/seasons/2025/types/1/groups/~a?lang=en&region=us" id)) )
        (let ( (json (espn-get-page espn-host-core page port->json-obj)) )
          (if (not json) (throw 'unable-to-find-conference))
          (if (not (json-ref isConference json)) (throw 'id-does-not-identify-a-confernce))
          (let ( (abbrev (string->symbol (json-ref abbreviation json))) )
            (hash-set! conf-map id abbrev)
            abbrev))))))

(define (lookup-div-id id)
  (let ( (div-sym (hash-ref div-map id)) )
    (if div-sym
      div-sym
      (let ( (page (format #f "v2/sports/football/leagues/nfl/seasons/2025/types/1/groups/~a?lang=en&region=us" id)) )
        (let ( (json (espn-get-page espn-host-core page port->json-obj)) )
          (if (not json) (throw 'unable-to-find-division))
          (if (json-ref isConference json) (throw 'id-does-not-identify-a-division))
          (let ( (abbrev (string->symbol (json-ref abbreviation json))) )
            (hash-set! div-map id abbrev)
            abbrev))))))

(define (lookup-division url)
  (let ( (cached (hash-ref url-map url)) )
    (if cached
      cached
      (let ( (div-json (espn-get-url url port->json-obj)) )
        (let ( (conf-url (json-ref parent.$ref div-json)) )
          (let ( (conf-json (espn-get-url conf-url port->json-obj)) )
            (let ( (pair (cons (string->symbol (json-ref abbreviation conf-json))
                               (string->symbol (json-ref abbreviation div-json)))) )
              (hash-set! url-map url pair)
              pair)))))))

;;
;; Front facing methods
;;

(define (espn-get-teams)
  (let ( (json (espn-get-page espn-host-core "v2/sports/football/leagues/nfl/teams?limit=320" port->json-obj)) )
    (let ( (team-urls (map (lambda (x) (json-ref $ref x)) (json-ref items json))) )
      (map slurp-team team-urls))))

(define (slurp-team team-url)
  (let ( (json (espn-get-url team-url port->json-obj)) )
    (let ( (division (lookup-division (json-ref groups.$ref json))) )
      (let ( (id (string->number (json-ref id json))) )
        (if (not (get-team id))
          (make-instance <nfl-team>
                         #:id id
                         #:nick (string->symbol (json-ref abbreviation json))
                         #:name (json-ref name json)
                         #:color (read-espn-color (json-ref color json))
                         #:alt-color (read-espn-color (json-ref alternateColor json))
                         #:conf (car division)
                         #:div (cdr division)))))))

; (espn-get-teams)

;;
;; quick and dirty persistance
;;

;; REFRESH TEAMS *******************************************************************************************************

(define league-mod '(data league))
(define league-mod-file (format #f "~a/.nfldb/cache/~a.scm"
                                (getenv "HOME")
                                (string-join (map symbol->string league-mod) "/")))

(define (write-teams-module-file teams out)
  (define (write-team t)
    (format out "~%")
    (write-constructor t out)
    (format out "~%"))
  (define (write-div c d)
    (format #t ";; ~a ~a~%" c d)
    (map write-team (get-div c d))
    (format #t "~%"))
  (format #t "(define-module ~a~%" league-mod)
  (format #t " ;; DO NOT EDIT! Generated by sandbox/espn.scm write-teams-module-file~%")
  (format #t " ;; Just a hack for now to keep from having to download static data every time the script is loaded~%")
  (format #t "~%")
  (format #t " #:use-module (oop goops)~%")
  (format #t " #:use-module (bad-cat utils)~%")
  (format #t " #:use-module (bad-cat nfldb team)~%")
  (format #t ")~%")
  (format #t "~%")
  (map (lambda (c)
         (map (lambda (d) (write-div c d))
              '(NORTH SOUTH EAST WEST)))
       '(AFC NFC)))

(define-method (refresh-team-module)
  (espn-get-teams)
  (with-output-to-file league-mod-file (lambda () (write-teams-module-file (all-nfl-teams) (current-output-port)))))

;; REFRESH SCHEDULE ****************************************************************************************************

(define (week-mod year week)
  `(data sched
            ,(string->symbol (format #f "year-~a" year))
            ,(string->symbol (format #f "week-~2,'0d" week))))
(define (week-mod-file year week)
  (format #f "~a/.nfldb/cache/~a.scm" (getenv "HOME") (string-join (map symbol->string (week-mod year week)) "/")))
(define (write-week-schedule games year week out)
  (define (write-game g)
    (format out "~%")
    (format out "(cache-add-game-for-week ")
    (write-constructor g out)
    (format out " ~a ~a)~%" year week)
    (format out "~%"))
  (format out "(define-module ~a~%" (week-mod year week))
  (format out " ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file~%")
  (format out " ;; Just a hack for now to keep from having to download static data every time the script is loaded~%")
  (format out " ;; Number of games: ~a~%" (length games))
  (format out "~%")
  (format out " #:use-module (oop goops)~%")
  (format out " #:use-module (bad-cat utils)~%")
  (format out " #:use-module (bad-cat nfldb team)~%")
  (format out " #:use-module (bad-cat nfldb game)~%")
  (format out " #:use-module (bad-cat nfldb cache)~%")
  (format out ")~%")
  (format out "~%")
  (map write-game (sort games game-date<?)))

(define-method (refresh-week-module year week)
  (with-output-to-file
    (week-mod-file year week)
    (let ( (games (ds-get-games year week)) )
      (lambda () (write-week-schedule games year week (current-output-port))))))

