;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Put together a week preview display
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-modules (oop goops))
(use-modules (cairo))

; (use-modules (srfi srfi-19))

(use-modules (g-golf))

(use-modules (bad-cat utils))

(use-modules (bad-cat nfldb game))
(use-modules (bad-cat nfldb team))

(use-modules (bad-cat nfldb data))

(use-modules (bad-cat nfldb ui init))

(use-modules (bad-cat nfldb cache schedule))
(use-modules (bad-cat nfldb cache result))
(use-modules (bad-cat nfldb cache league))
(use-modules (bad-cat nfldb cache standings))
(use-modules (bad-cat nfldb))

(define (show-week-preview-window app component-proc year-no week-no)
  (let ( (window (make-instance <gtk-application-window>
                                      #:title (format #f "Preview: week ~a" week-no)
                                      #:icon "/bad-cat/nfldb/NFL"
                                      #:application app)) )

    (gtk-style-context-add-provider-for-display (gdk-display-get-default) nfldb-css-provider 0)

    (set-child window (component-proc year-no week-no))

    (present window)))

;; Primary Values
(define top-margin      10)
(define bottom-margin   10)
(define left-margin     10)
(define right-margin    10)
(define box-height      32)
(define info-width      48)
(define team-space      4)
(define div-space       16)
(define graph-width     500)
(define moor-offset     8)

;; Derived Values
(define box-width (+ info-width (* 2 box-height)))
(define diagram-width (+ (* 2 box-width) graph-width))
(define total-width (+ diagram-width left-margin right-margin))

(define diagram-height (+ (* 16 box-height)
                          (* 3  div-space)
                          (* 12 team-space)))
(define total-height (+ diagram-height top-margin bottom-margin))

(define (get-preview-diagram year-no week-no)
  (let ( (drawing-area (make-instance <gtk-drawing-area>
                                      #:content-height total-height
                                      #:content-width total-width)) )
    (let ( (game-draw-func (make-preview-draw-func year-no week-no)) )
      (gtk-drawing-area-set-draw-func drawing-area game-draw-func #f #f)
      drawing-area)))

(define (nfldb-show-preview week-no)
  (define (proc app) (show-week-preview-window app get-preview-diagram (current-season) week-no))
  (if (not (and (>= week-no 1) (<= week-no 18)))
    (throw 'week-out-of-range week-no))
  (let ( (app (make <gtk-application> #:application-id "bad-cat.nfldb.game-digram")) )
    (connect app 'activate proc)
    (g-application-run app '())))

(define (make-preview-draw-func year-no week-no)
  (lambda (drawing-area cr-ptr width height user-data)
    (let ( (cr (cairo-pointer->context cr-ptr)) )
      (let ( (box-locations (draw-conferences cr))
             (games (get-games year-no week-no)) )
        (hash-map->list (lambda (a b) (format #t "~8a => ~a~%" a b) #t) box-locations)
        ; (draw-matches cr box-locations games)
        (draw-matches-newly cr box-locations games)))))

(define (calc-px-size loc0 loc1)
  (let ( (d0 (box.div-no loc0))
         (t0 (box.team-no loc0))
         (d1 (box.div-no loc1))
         (t1 (box.team-no loc1)) )
      (let ( (same-conf? (eq? (box.afc? loc0) (box.afc? loc1)))
             (span (+ (abs (- (+ t0 (* 4 d0)) (+ t1 (* 4 d1))))
                      (* 2 (abs (- d0 d1))))) )
        (if same-conf?
            (* span 8)
            (+ (floor (/ graph-width 4)) (* span 10))))))

(define (draw-match-line-1 cr home-loc away-loc)
  (define (calc-xm x0 x1)
    (if (eq? (box.afc? home-loc) (box.afc? away-loc))
        ;; Same Conference
        (if (box.afc? home-loc)
            (+ box-width 60)
            (+ box-width (- graph-width 60)))
        ;; Different Conferences
        (floor (/ (+ x0 x1) 2))))
  (let* ( (x0 (mooring-x home-loc))
          (y0 (mooring-y home-loc))
          (x1 (mooring-x away-loc))
          (y1 (mooring-y away-loc))
          (xm (calc-xm x0 x1))
          (ym (floor (/ (+ y0 y1) 2)))
          (home-rank (box-rank home-loc))
          (away-rank (box-rank away-loc))
          (afc-0? (box.afc? home-loc))
          (afc-1? (box.afc? away-loc)) )
    (let ( (px-size (calc-px-size home-loc away-loc)) )
      (let ( (px0 (if afc-0? (+ x0 px-size) (- x0 px-size)))
             (px1 (if afc-1? (+ x1 px-size) (- x1 px-size))) )
        (format #t "rank of ~a = ~2d, ~a = ~2d~%" home-loc home-rank away-loc away-rank)
        (let ( (y0m (if (eq? home-rank away-rank) 0 (if (< home-rank away-rank) 20 -20))))
          (cairo-move-to cr x0 y0)
          (cairo-curve-to cr px0 y0 xm (- ym y0m) xm ym)
          (cairo-curve-to cr xm (+ ym y0m) px1 y1 x1 y1)
          ; (format #t "drawing match from ~a (~a, ~a) to ~a (~a, ~a)~%" home-name x0 y0 away-name x1 y1)
          (cairo-stroke cr))))))
(define (draw-match-line cr home-loc away-loc)
  (let ( (x0 (mooring-x home-loc))
         (y0 (mooring-y home-loc))
         (x1 (mooring-x away-loc))
         (y1 (mooring-y away-loc))
         (afc-0? (box.afc? home-loc))
         (afc-1? (box.afc? away-loc)) )
    (let ( (px-size (calc-px-size home-loc away-loc)) )
      (let ( (px0 (if afc-0? (+ x0 px-size) (- x0 px-size)))
             (px1 (if afc-1? (+ x1 px-size) (- x1 px-size))) )
        (cairo-move-to cr x0 y0)
        (cairo-curve-to cr px0 y0 px1 y1 x1 y1)
        ; (format #t "drawing match from ~a (~a, ~a) to ~a (~a, ~a)~%" home-name x0 y0 away-name x1 y1)
        (cairo-stroke cr)))))

(define (draw-matches cr box-locations games)
  (define (draw-next-match todo)
    (if (not (null? todo))
        (let ( (game (car todo)) )
          (let ( (home-name (slot-ref game 'home-team))
                 (away-name (slot-ref game 'away-team)) )
            (let ( (home-loc (hash-ref box-locations home-name))
                   (away-loc (hash-ref box-locations away-name)) )
              (draw-match-line-1 cr home-loc away-loc)))
          (draw-next-match (cdr todo)))))
  (cairo-set-line-width cr 2)
  (cairo-set-source-rgb cr 0 0.4 0.2)
  (draw-next-match games))

(define (draw-team-box cr afc? team div-num team-num)
  (let ( (y (+ top-margin
               (* div-num (+ (* 4 box-height)
                             div-space
                             (* 3 team-space)))
               (* team-num (+ box-height team-space))))
         (x (+ left-margin (if afc? 0 (+ box-width graph-width)))) )
    ; (format #t "drawing team box for ~3a at ~a ~a~%" team x y)

    (cairo-rectangle cr x y box-width box-height)
    (cairo-stroke cr)
    ; (format #t "about to get team name for ~a~%" team)
    (let ( (name (slot-ref team 'name))
           (name-x (+ x 20))
           (name-y (+ y (floor (/ box-height 2)))) )
      (cairo-move-to cr name-x name-y)
      ; (format #t "about to draw text ~a~%" name)
      (cairo-show-text cr name))))

(define-class <box-location> ()
  (afc?       #:init-keyword    #:afc?
              #:getter          box.afc?)
  (div-no     #:init-keyword    #:div-no
              #:getter          box.div-no)
  (team-no    #:init-keyword    #:team-no
              #:getter          box.team-no)
)

(define-method (write (loc <box-location>) out)
  (format out "[~a : Div ~a, Team ~a]" (if (box.afc? loc) 'AFC 'NFC) (box.div-no loc) (box.team-no loc)))

(define-method (mooring-x (loc <box-location>))
  (if (box.afc? loc)
      (+ left-margin box-width moor-offset)
      (- (+ left-margin box-width graph-width) moor-offset)))

(define-method (mooring-y (loc <box-location>))
  (+ top-margin
     (* (box.div-no loc)
        (+ (* 4 box-height)
           (* 3 team-space)
           div-space))
     (* (box.team-no loc)
        (+ box-height
           team-space))
     (+ (floor (/ box-height 2)))))

(define-method (box-rank (loc <box-location>))
  (+ (* 4 (box.div-no loc)) (box.team-no loc)))

(define (draw-conferences cr)
  (cairo-set-line-width cr 1)
  (cairo-set-source-rgb cr 0 0.4 0)
  (let ( (box-positions (make-hash-table)) )
    (define (draw-division afc? div-no teams)
      (define (proc team-no todo)
        (if (not (null? todo))
            (let ( (team-nick (car todo))
                   (box-pos (make-instance <box-location> #:afc? afc? #:div-no div-no #:team-no team-no)) )
              (hash-set! box-positions team-nick box-pos)
              (draw-team-box cr afc? (get-team team-nick) div-no team-no)
              (proc (1+ team-no) (cdr todo)))))
      (proc 0 teams))
    (define (draw-conference afc?)
      (let ( (conf (if afc? 'AFC 'NFC)) )
        (define (proc div-no todo)
          (if (not (null? todo))
              (let ( (next (car todo)) )
                (let ( (teams (map car (get-standings conf next))) )
                  (draw-division afc? div-no teams))
                (proc (1+ div-no) (cdr todo)))))
        (proc 0 '(EAST NORTH SOUTH WEST))))

    (cairo-set-source-rgb cr 0.4 0 0)
    (draw-conference #t)
    (cairo-set-source-rgb cr 0 0 0.4)
    (draw-conference #f)
    box-positions))

(define-class <match> ()
  (game       #:init-keyword  #:game
              #:getter        match.game)
  (home-loc   #:init-keyword  #:home-loc
              #:getter        match.home-loc)
  (home-team  #:init-keyword  #:home
              #:getter        match.home)
  (away-loc   #:init-keyword  #:away-loc
              #:getter        match.away-loc)
  (away-team  #:init-keyword  #:away
              #:getter        match.away)
)

(define-method (first-loc (m <match>))
  ; (format #t "first-loc: (box-rank (match.home-loc m)) = ~a, (box-rank (match.away-loc m)) = ~a~%"
  ;         (box-rank (match.home-loc m)) (box-rank (match.away-loc m)))
  (if (< (box-rank (match.home-loc m)) (box-rank (match.away-loc m)))
      (match.home-loc m)
      (match.away-loc m)))

(define-method (second-loc (m <match>))
  ; (format #t "second-loc: (box-rank (match.home-loc m)) = ~a, (box-rank (match.away-loc m)) = ~a~%"
  ;         (box-rank (match.home-loc m)) (box-rank (match.away-loc m)))
  (if (> (box-rank (match.home-loc m)) (box-rank (match.away-loc m)))
      (match.home-loc m)
      (match.away-loc m)))

(define-method (loc-span (m <match>))
  (abs (- (box-rank (match.home-loc m)) (box-rank (match.away-loc m)))))

(define-method (div-match? (m <match>))
  (eq? (team.div (match.home m)) (team.div (match.away m))))

(define (compare-matches m1 m2)
  (let ( (r1 (box-rank (first-loc m1)))
         (r2 (box-rank (first-loc m2))) )
    (format #t "compare-matches: r1 = ~a, r2 = ~a, span1 = ~a, span2 = ~a~%" r1 r2 (loc-span m1) (loc-span m2))
    (if (eq? r1 r2)
        (if (< (loc-span m1) (loc-span m2)) m1 m2)
        (if (< r1 r2) m1 m2))))

(define-class <lane> ()
  (matches    #:init-form    '()
              #:getter       lane.matches)
)

(define-method (write (l <lane>) out)
  (define (write-matches sep todo)
    (if (null? todo)
        (format out "]")
        (let ( (next (car todo)) )
          (format out "~a ~a-~a " sep (box-rank (first-loc next)) (box-rank (second-loc next)))
          (write-matches "|" (cdr todo)))))
  (let ( (matches (lane.matches l)) )
    (format out "[ (~a) " (length matches))
    (write-matches ":" matches)))

(define-method (add-match (l <lane>) (m <match>))
  (let ( (end (box-rank (second-loc m))) )
    (slot-set! l 'matches (append (lane.matches l) (list m)))))

(define (span-fits-in-lane? start end todo)
  (if (null? todo)
      #t
      (let ( (next (car todo)) )
        (if (or (< end (box-rank (first-loc next)))
                (> start (box-rank (second-loc next))))
            (span-fits-in-lane? start end (cdr todo))
            #f))))

(define (find-available-lane lanes start end)
  (format #t "find-available-lane: called on ~a, ~a-~a~%" lanes start end)
  (if (null? lanes)
      (begin
        (format #t "find-available-lane: unable to find a lane for ~a-~a~%" start end)
        #f)
      (let ( (next (car lanes)) )
        ; (format #t "find-available-lane: range = ~a-~a, (lane.through next) = ~a~%" start end (lane.through next))
        (if (span-fits-in-lane? start end (lane.matches next))
            (begin
              (format #t "find-available-lane: found lane ~a for ~a~%" next start)
              next)
            (find-available-lane (cdr lanes) start end)))))

(define (sort-league-lanes lanes)
  ;; TODO: implement sort
  lanes)

(define (draw-matches-newly cr box-locations games)
  (define (game-conf g)
    (let ( (h (slot-ref g 'home-team))
           (a (slot-ref g 'away-team)) )
      (let ( (h-team (get-team h))
             (a-team (get-team a)) )
        (if (eq? (team.conf h-team) (team.conf a-team)) (team.conf h-team) #f))))
  (define (afc-only g) (eq? 'AFC (game-conf g)))
  (define (nfc-only g) (eq? 'NFC (game-conf g)))
  (define (league-only g) (not (game-conf g)))
  (define (create-match game)
    (let ( (home-loc (hash-ref box-locations (slot-ref game 'home-team)))
           (away-loc (hash-ref box-locations (slot-ref game 'away-team)))
           (home (get-team (slot-ref game 'home-team)))
           (away (get-team (slot-ref game 'away-team))) )
      (make-instance <match> #:game game #:home home #:away away #:home-loc home-loc #:away-loc away-loc)))
  (let ( (afc-games (sort (map create-match (filter afc-only games)) compare-matches))
         (nfc-games (sort (map create-match (filter nfc-only games)) compare-matches))
         (league-games (sort (map create-match (filter league-only games)) compare-matches)) )
    (let ( (div-afc '())
           (conf-afc '())
           (league '())
           (straight '())
           (conf-nfc '())
           (div-nfc '()) )
      (define (pop-afc-lanes todo)
        ; (format #t "pop-afc-lanes called on ~a~%" todo)
        (if (not (null? todo))
            (let ( (next (car todo)) )
              (if (div-match? next)
                  (let ( (lane (find-available-lane div-afc (box-rank (first-loc next)) (box-rank (second-loc next)))) )
                    ; (format #t "nfc div    : adding ~a - ~a~%" (box-rank (first-loc next)) (box-rank (second-loc next)))
                    (if lane
                        (add-match lane next)
                        (let ( (new-lane (make-instance <lane>)) )
                          (add-match new-lane next)
                          (set! div-afc (cons new-lane div-afc)))))
                  (let ( (lane (find-available-lane conf-afc (box-rank (first-loc next)) (box-rank (second-loc next)))) )
                    ; (format #t "nfc conf    : adding ~a - ~a~%" (box-rank (first-loc next)) (box-rank (second-loc next)))
                    (if lane
                        (add-match lane next)
                        (let ( (new-lane (make-instance <lane>)) )
                          (add-match new-lane next)
                          (set! conf-afc (cons new-lane conf-afc))))))
              (pop-afc-lanes (cdr todo)))))
      (define (pop-nfc-lanes todo)
        ; (format #t "pop-nfc-lanes called on ~a~%" todo)
        (if (not (null? todo))
            (let ( (next (car todo)) )
              (if (div-match? next)
                  (let ( (lane (find-available-lane div-nfc (box-rank (first-loc next)) (box-rank (second-loc next)))) )
                    ; (format #t "afc div    : adding ~a - ~a~%" (box-rank (first-loc next)) (box-rank (second-loc next)))
                    (if lane
                        (add-match lane next)
                        (let ( (new-lane (make-instance <lane>)) )
                          (add-match new-lane next)
                          (set! div-nfc (cons new-lane div-nfc)))))
                  (let ( (lane (find-available-lane conf-nfc (box-rank (first-loc next)) (box-rank (second-loc next)))) )
                    ; (format #t "afc conf    : adding ~a - ~a~%" (box-rank (first-loc next)) (box-rank (second-loc next)))
                    (if lane
                        (add-match lane next)
                        (let ( (new-lane (make-instance <lane>)) )
                          (add-match new-lane next)
                          (set! conf-nfc (cons new-lane conf-nfc))))))
              (pop-nfc-lanes (cdr todo)))))
      (define (pop-league-lanes todo)
        ; (format #t "pop-league-lanes called on ~a~%" todo)
        (if (null? todo)
            (set! league (sort-league-lanes league))
            (let ( (next (car todo)) )
              ; (format #t "league    : adding ~a - ~a~%" (box-rank (first-loc next)) (box-rank (second-loc next)))
              (if (eq? (box-rank (first-loc next)) (box-rank (second-loc next)))
                  (begin
                    (if (null? straight)
                      (set! straight (list (make-instance <lane>))))
                    (add-match (car straight) next))
                  (let ( (lane (find-available-lane league (box-rank (first-loc next)) (box-rank (second-loc next)))) )
                      (if lane
                          (add-match lane next)
                          (let ( (new-lane (make-instance <lane>)) )
                            (add-match new-lane next)
                            (set! league (cons new-lane league))))))
              (pop-league-lanes (cdr todo)))))
      (define (draw-conf-matches afc? lane-no offset spacing lanes)
        (if (not (null? lanes))
          (let ( (next (car lanes)) )
            (let ( (x0 (+ box-width left-margin (if afc? 0 graph-width)))
                   (x1 (+ box-width
                          left-margin
                          (if afc?
                              (+ offset (* lane-no spacing))
                              (- graph-width (+ offset (* lane-no spacing)))))) )
              (define (draw-conf-match m)
                (let ( (y0 (mooring-y (first-loc m)))
                       (y1 (mooring-y (second-loc m))) )
                  (cairo-move-to cr x0 y0)
                  (cairo-line-to cr x1 y0)
                  (cairo-line-to cr x1 y1)
                  (cairo-line-to cr x0 y1)
                  (cairo-stroke cr)))
              (map draw-conf-match (lane.matches next)))
          (draw-conf-matches afc? (1+ lane-no) offset spacing (cdr lanes)))))
      (define (draw-league-matches spacing lanes)
        (let ( (start-x (+ box-width
                           left-margin
                           (/ (- graph-width (* spacing (- (length lanes) 1))) 2))) )
          (define (draw-league-lanes offset lanes)
            (if (not (null? lanes))
                (let ( (next (car lanes)))
                  (let ( (xm (+ start-x (* spacing offset))) )
                    (define (draw-match m)
                      (let ( (l0 (first-loc m))
                             (l1 (second-loc m)) )
                        (let ( (x0 (if (box.afc? l0)
                                       (+ box-width left-margin)
                                       (+ box-width left-margin graph-width)))
                               (x1 (if (box.afc? l1)
                                       (+ box-width left-margin)
                                       (+ box-width left-margin graph-width)))
                               (y0 (mooring-y l0))
                               (y1 (mooring-y l1)) )
                          (cairo-move-to cr x0 y0)
                          (cairo-line-to cr xm y0)
                          (cairo-line-to cr xm y1)
                          (cairo-line-to cr x1 y1)
                          (cairo-stroke cr))))
                    (map draw-match (lane.matches next)))
                  (draw-league-lanes (1+ offset) (cdr lanes)))))
          (draw-league-lanes 0 lanes)))
      (define (draw-straight-matches todo)
        (if (not (null? todo))
            (let ( (next (car todo)) )
              (let ( (y (mooring-y (first-loc next))) )
                (cairo-move-to cr (+ left-margin box-width) y)
                (cairo-line-to cr (+ left-margin box-width graph-width) y)
                (cairo-stroke cr))
              (draw-straight-matches (cdr todo)))))

      (format #t "draw-matches-newly: about to populate afc lanes~%")
      (pop-afc-lanes afc-games)
      (format #t "draw-matches-newly: about to populate nfc lanes~%")
      (pop-nfc-lanes nfc-games)
      (format #t "draw-matches-newly: about to populate league lanes~%")
      (pop-league-lanes league-games)
      (format #t "draw-matches-newly: finished populating lanes~%")

      (format #t "div-afc   : ~a~%" div-afc)
      (format #t "conf-afc  : ~a~%" conf-afc)
      (format #t "league    : ~a~%" league)
      (format #t "straight  : ~a~%" straight)
      (format #t "conf-nfc  : ~a~%" conf-nfc)
      (format #t "div-nfc   : ~a~%" div-nfc)

      (cairo-set-source-rgb cr 0 0.1 0)

      (cairo-set-line-width cr 3)
      (draw-conf-matches #t 0 20 20 div-afc)

      (cairo-set-line-width cr 1.5)
      (draw-conf-matches #t 0 60 20 conf-afc)

      (cairo-set-line-width cr 0.5)
      (draw-league-matches 30 league)
      (if (not (null? straight)) (draw-straight-matches (lane.matches (car straight))))

      (cairo-set-line-width cr 1.5)
      (draw-conf-matches #f 0 60 20 conf-nfc)

      (cairo-set-line-width cr 3)
      (draw-conf-matches #f 0 20 20 div-nfc)
      )))

