#! /bin/sh
# -*- mode: scheme; coding: utf-8 -*-
# echo "exec guile -L $(dirname $0) -e main -s $0 $@"
exec guile -L $(dirname $0) -e main -s "$0" "$@"
!#

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Run the main nfldb project
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-modules (bad-cat nfldb ui))
(use-modules (bad-cat nfldb data))

(define (get-parameters args)
  (let ( (params (make-hash-table)) )
      (hash-set! params 'my-team (if (null? args) 'PHI (string->symbol (string-upcase (car args)))))

      params))

(define (main args)
  (let ( (file   (car args))
         (params (get-parameters (cdr args))) )
    (nfldb-show-overview-for (hash-ref params 'my-team))))

