#!/bin/bash
######################################################################################################################### export db
########################################################################################################################

# A User with Read access to the database
USER=custodial

# Run from owning directory
cd $(dirname $0)

mysqldump -u $USER nfl > nfl.sql

