(define-module (bad-cat nfldb data sched year-2023 week-07)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 13

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547483
               #:name           "Jacksonville Jaguars at New Orleans Saints"
               #:short-name     "JAX @ NO"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1697760900)
               #:home           'NO
               #:away           'JAX
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547490
               #:name           "Las Vegas Raiders at Chicago Bears"
               #:short-name     "LV @ CHI"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1697994000)
               #:home           'CHI
               #:away           'LV
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547484
               #:name           "Cleveland Browns at Indianapolis Colts"
               #:short-name     "CLE @ IND"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1697994000)
               #:home           'IND
               #:away           'CLE
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547485
               #:name           "Buffalo Bills at New England Patriots"
               #:short-name     "BUF @ NE"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1697994000)
               #:home           'NE
               #:away           'BUF
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547486
               #:name           "Washington Commanders at New York Giants"
               #:short-name     "WSH @ NYG"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1697994000)
               #:home           'NYG
               #:away           'WSH
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547491
               #:name           "Atlanta Falcons at Tampa Bay Buccaneers"
               #:short-name     "ATL @ TB"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1697994000)
               #:home           'TB
               #:away           'ATL
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547489
               #:name           "Detroit Lions at Baltimore Ravens"
               #:short-name     "DET @ BAL"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1697994000)
               #:home           'BAL
               #:away           'DET
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547492
               #:name           "Pittsburgh Steelers at Los Angeles Rams"
               #:short-name     "PIT @ LAR"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1698005100)
               #:home           'LAR
               #:away           'PIT
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547493
               #:name           "Arizona Cardinals at Seattle Seahawks"
               #:short-name     "ARI @ SEA"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1698005100)
               #:home           'SEA
               #:away           'ARI
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547487
               #:name           "Green Bay Packers at Denver Broncos"
               #:short-name     "GB @ DEN"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1698006300)
               #:home           'DEN
               #:away           'GB
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547488
               #:name           "Los Angeles Chargers at Kansas City Chiefs"
               #:short-name     "LAC @ KC"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1698006300)
               #:home           'KC
               #:away           'LAC
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547494
               #:name           "Miami Dolphins at Philadelphia Eagles"
               #:short-name     "MIA @ PHI"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1698020400)
               #:home           'PHI
               #:away           'MIA
)
 2023 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547495
               #:name           "San Francisco 49ers at Minnesota Vikings"
               #:short-name     "SF @ MIN"
               #:year           2023
               #:week           6
               #:time           (secs->gametime 1698106500)
               #:home           'MIN
               #:away           'SF
)
 2023 7)

