(define-module (bad-cat nfldb data sched year-2023 week-02)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547410
               #:name           "Minnesota Vikings at Philadelphia Eagles"
               #:short-name     "MIN @ PHI"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694736900)
               #:home           'PHI
               #:away           'MIN
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547417
               #:name           "Green Bay Packers at Atlanta Falcons"
               #:short-name     "GB @ ATL"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'ATL
               #:away           'GB
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547411
               #:name           "Las Vegas Raiders at Buffalo Bills"
               #:short-name     "LV @ BUF"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'BUF
               #:away           'LV
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547412
               #:name           "Baltimore Ravens at Cincinnati Bengals"
               #:short-name     "BAL @ CIN"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'CIN
               #:away           'BAL
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547418
               #:name           "Seattle Seahawks at Detroit Lions"
               #:short-name     "SEA @ DET"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'DET
               #:away           'SEA
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547414
               #:name           "Los Angeles Chargers at Tennessee Titans"
               #:short-name     "LAC @ TEN"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'TEN
               #:away           'LAC
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547420
               #:name           "Chicago Bears at Tampa Bay Buccaneers"
               #:short-name     "CHI @ TB"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'TB
               #:away           'CHI
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547413
               #:name           "Kansas City Chiefs at Jacksonville Jaguars"
               #:short-name     "KC @ JAX"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'JAX
               #:away           'KC
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547419
               #:name           "Indianapolis Colts at Houston Texans"
               #:short-name     "IND @ HOU"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694970000)
               #:home           'HOU
               #:away           'IND
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547422
               #:name           "San Francisco 49ers at Los Angeles Rams"
               #:short-name     "SF @ LAR"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694981100)
               #:home           'LAR
               #:away           'SF
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547421
               #:name           "New York Giants at Arizona Cardinals"
               #:short-name     "NYG @ ARI"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694981100)
               #:home           'ARI
               #:away           'NYG
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547415
               #:name           "New York Jets at Dallas Cowboys"
               #:short-name     "NYJ @ DAL"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694982300)
               #:home           'DAL
               #:away           'NYJ
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547416
               #:name           "Washington Commanders at Denver Broncos"
               #:short-name     "WSH @ DEN"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694982300)
               #:home           'DEN
               #:away           'WSH
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547423
               #:name           "Miami Dolphins at New England Patriots"
               #:short-name     "MIA @ NE"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1694996400)
               #:home           'NE
               #:away           'MIA
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547425
               #:name           "New Orleans Saints at Carolina Panthers"
               #:short-name     "NO @ CAR"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1695078900)
               #:home           'CAR
               #:away           'NO
)
 2023 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547424
               #:name           "Cleveland Browns at Pittsburgh Steelers"
               #:short-name     "CLE @ PIT"
               #:year           2023
               #:week           1
               #:time           (secs->gametime 1695082500)
               #:home           'PIT
               #:away           'CLE
)
 2023 2)

