(define-module (bad-cat nfldb data sched year-2023 week-08)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547496
               #:name           "Tampa Bay Buccaneers at Buffalo Bills"
               #:short-name     "TB @ BUF"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698365700)
               #:home           'BUF
               #:away           'TB
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547505
               #:name           "Los Angeles Rams at Dallas Cowboys"
               #:short-name     "LAR @ DAL"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'DAL
               #:away           'LAR
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547506
               #:name           "Minnesota Vikings at Green Bay Packers"
               #:short-name     "MIN @ GB"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'GB
               #:away           'MIN
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547500
               #:name           "Atlanta Falcons at Tennessee Titans"
               #:short-name     "ATL @ TEN"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'TEN
               #:away           'ATL
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547507
               #:name           "New Orleans Saints at Indianapolis Colts"
               #:short-name     "NO @ IND"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'IND
               #:away           'NO
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547497
               #:name           "New England Patriots at Miami Dolphins"
               #:short-name     "NE @ MIA"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'MIA
               #:away           'NE
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547498
               #:name           "New York Jets at New York Giants"
               #:short-name     "NYJ @ NYG"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'NYG
               #:away           'NYJ
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547499
               #:name           "Jacksonville Jaguars at Pittsburgh Steelers"
               #:short-name     "JAX @ PIT"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'PIT
               #:away           'JAX
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547508
               #:name           "Philadelphia Eagles at Washington Commanders"
               #:short-name     "PHI @ WSH"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'WSH
               #:away           'PHI
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547504
               #:name           "Houston Texans at Carolina Panthers"
               #:short-name     "HOU @ CAR"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698598800)
               #:home           'CAR
               #:away           'HOU
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547509
               #:name           "Cleveland Browns at Seattle Seahawks"
               #:short-name     "CLE @ SEA"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698609900)
               #:home           'SEA
               #:away           'CLE
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547502
               #:name           "Kansas City Chiefs at Denver Broncos"
               #:short-name     "KC @ DEN"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698611100)
               #:home           'DEN
               #:away           'KC
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547501
               #:name           "Baltimore Ravens at Arizona Cardinals"
               #:short-name     "BAL @ ARI"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698611100)
               #:home           'ARI
               #:away           'BAL
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547503
               #:name           "Cincinnati Bengals at San Francisco 49ers"
               #:short-name     "CIN @ SF"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698611100)
               #:home           'SF
               #:away           'CIN
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547510
               #:name           "Chicago Bears at Los Angeles Chargers"
               #:short-name     "CHI @ LAC"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698625200)
               #:home           'LAC
               #:away           'CHI
)
 2023 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547511
               #:name           "Las Vegas Raiders at Detroit Lions"
               #:short-name     "LV @ DET"
               #:year           2023
               #:week           7
               #:time           (secs->gametime 1698711300)
               #:home           'DET
               #:away           'LV
)
 2023 8)

