(define-module (bad-cat nfldb data sched year-2023 week-12)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547552
               #:name           "Green Bay Packers at Detroit Lions"
               #:short-name     "GB @ DET"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1700764200)
               #:home           'DET
               #:away           'GB
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547551
               #:name           "Washington Commanders at Dallas Cowboys"
               #:short-name     "WSH @ DAL"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1700778600)
               #:home           'DAL
               #:away           'WSH
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547553
               #:name           "San Francisco 49ers at Seattle Seahawks"
               #:short-name     "SF @ SEA"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1700792400)
               #:home           'SEA
               #:away           'SF
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547242
               #:name           "Miami Dolphins at New York Jets"
               #:short-name     "MIA @ NYJ"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1700859600)
               #:home           'NYJ
               #:away           'MIA
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547559
               #:name           "New Orleans Saints at Atlanta Falcons"
               #:short-name     "NO @ ATL"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701025200)
               #:home           'ATL
               #:away           'NO
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547554
               #:name           "Pittsburgh Steelers at Cincinnati Bengals"
               #:short-name     "PIT @ CIN"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701025200)
               #:home           'CIN
               #:away           'PIT
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547561
               #:name           "Carolina Panthers at Tennessee Titans"
               #:short-name     "CAR @ TEN"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701025200)
               #:home           'TEN
               #:away           'CAR
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547556
               #:name           "Tampa Bay Buccaneers at Indianapolis Colts"
               #:short-name     "TB @ IND"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701025200)
               #:home           'IND
               #:away           'TB
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547560
               #:name           "New England Patriots at New York Giants"
               #:short-name     "NE @ NYG"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701025200)
               #:home           'NYG
               #:away           'NE
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547555
               #:name           "Jacksonville Jaguars at Houston Texans"
               #:short-name     "JAX @ HOU"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701025200)
               #:home           'HOU
               #:away           'JAX
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547563
               #:name           "Cleveland Browns at Denver Broncos"
               #:short-name     "CLE @ DEN"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701036300)
               #:home           'DEN
               #:away           'CLE
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547562
               #:name           "Los Angeles Rams at Arizona Cardinals"
               #:short-name     "LAR @ ARI"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701036300)
               #:home           'ARI
               #:away           'LAR
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547557
               #:name           "Kansas City Chiefs at Las Vegas Raiders"
               #:short-name     "KC @ LV"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701037500)
               #:home           'LV
               #:away           'KC
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547558
               #:name           "Buffalo Bills at Philadelphia Eagles"
               #:short-name     "BUF @ PHI"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701037500)
               #:home           'PHI
               #:away           'BUF
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547564
               #:name           "Baltimore Ravens at Los Angeles Chargers"
               #:short-name     "BAL @ LAC"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701051600)
               #:home           'LAC
               #:away           'BAL
)
 2023 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547565
               #:name           "Chicago Bears at Minnesota Vikings"
               #:short-name     "CHI @ MIN"
               #:year           2023
               #:week           11
               #:time           (secs->gametime 1701137700)
               #:home           'MIN
               #:away           'CHI
)
 2023 12)

