(define-module (bad-cat nfldb data sched year-2023 week-16)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547609
               #:name           "New Orleans Saints at Los Angeles Rams"
               #:short-name     "NO @ LAR"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703211300)
               #:home           'LAR
               #:away           'NO
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547610
               #:name           "Cincinnati Bengals at Pittsburgh Steelers"
               #:short-name     "CIN @ PIT"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703370600)
               #:home           'PIT
               #:away           'CIN
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547611
               #:name           "Buffalo Bills at Los Angeles Chargers"
               #:short-name     "BUF @ LAC"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703383200)
               #:home           'LAC
               #:away           'BUF
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547616
               #:name           "Indianapolis Colts at Atlanta Falcons"
               #:short-name     "IND @ ATL"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703444400)
               #:home           'ATL
               #:away           'IND
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547614
               #:name           "Seattle Seahawks at Tennessee Titans"
               #:short-name     "SEA @ TEN"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703444400)
               #:home           'TEN
               #:away           'SEA
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547618
               #:name           "Detroit Lions at Minnesota Vikings"
               #:short-name     "DET @ MIN"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703444400)
               #:home           'MIN
               #:away           'DET
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547613
               #:name           "Washington Commanders at New York Jets"
               #:short-name     "WSH @ NYJ"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703444400)
               #:home           'NYJ
               #:away           'WSH
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547617
               #:name           "Green Bay Packers at Carolina Panthers"
               #:short-name     "GB @ CAR"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703444400)
               #:home           'CAR
               #:away           'GB
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547612
               #:name           "Cleveland Browns at Houston Texans"
               #:short-name     "CLE @ HOU"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703444400)
               #:home           'HOU
               #:away           'CLE
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547615
               #:name           "Jacksonville Jaguars at Tampa Bay Buccaneers"
               #:short-name     "JAX @ TB"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703455500)
               #:home           'TB
               #:away           'JAX
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547619
               #:name           "Arizona Cardinals at Chicago Bears"
               #:short-name     "ARI @ CHI"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703456700)
               #:home           'CHI
               #:away           'ARI
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547620
               #:name           "Dallas Cowboys at Miami Dolphins"
               #:short-name     "DAL @ MIA"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703456700)
               #:home           'MIA
               #:away           'DAL
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547621
               #:name           "New England Patriots at Denver Broncos"
               #:short-name     "NE @ DEN"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703470500)
               #:home           'DEN
               #:away           'NE
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547351
               #:name           "Las Vegas Raiders at Kansas City Chiefs"
               #:short-name     "LV @ KC"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703530800)
               #:home           'KC
               #:away           'LV
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547241
               #:name           "New York Giants at Philadelphia Eagles"
               #:short-name     "NYG @ PHI"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703543400)
               #:home           'PHI
               #:away           'NYG
)
 2023 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547622
               #:name           "Baltimore Ravens at San Francisco 49ers"
               #:short-name     "BAL @ SF"
               #:year           2023
               #:week           15
               #:time           (secs->gametime 1703556900)
               #:home           'SF
               #:away           'BAL
)
 2023 16)

