(define-module (bad-cat nfldb data sched year-2023 week-13)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 13

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547566
               #:name           "Seattle Seahawks at Dallas Cowboys"
               #:short-name     "SEA @ DAL"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701396900)
               #:home           'DAL
               #:away           'SEA
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547570
               #:name           "Indianapolis Colts at Tennessee Titans"
               #:short-name     "IND @ TEN"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701630000)
               #:home           'TEN
               #:away           'IND
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547567
               #:name           "Los Angeles Chargers at New England Patriots"
               #:short-name     "LAC @ NE"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701630000)
               #:home           'NE
               #:away           'LAC
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547572
               #:name           "Detroit Lions at New Orleans Saints"
               #:short-name     "DET @ NO"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701630000)
               #:home           'NO
               #:away           'DET
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547573
               #:name           "Atlanta Falcons at New York Jets"
               #:short-name     "ATL @ NYJ"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701630000)
               #:home           'NYJ
               #:away           'ATL
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547568
               #:name           "Arizona Cardinals at Pittsburgh Steelers"
               #:short-name     "ARI @ PIT"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701630000)
               #:home           'PIT
               #:away           'ARI
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547574
               #:name           "Miami Dolphins at Washington Commanders"
               #:short-name     "MIA @ WSH"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701630000)
               #:home           'WSH
               #:away           'MIA
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547571
               #:name           "Denver Broncos at Houston Texans"
               #:short-name     "DEN @ HOU"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701630000)
               #:home           'HOU
               #:away           'DEN
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547569
               #:name           "Carolina Panthers at Tampa Bay Buccaneers"
               #:short-name     "CAR @ TB"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701641100)
               #:home           'TB
               #:away           'CAR
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547575
               #:name           "Cleveland Browns at Los Angeles Rams"
               #:short-name     "CLE @ LAR"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701642300)
               #:home           'LAR
               #:away           'CLE
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547276
               #:name           "San Francisco 49ers at Philadelphia Eagles"
               #:short-name     "SF @ PHI"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701642300)
               #:home           'PHI
               #:away           'SF
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547576
               #:name           "Kansas City Chiefs at Green Bay Packers"
               #:short-name     "KC @ GB"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701656400)
               #:home           'GB
               #:away           'KC
)
 2023 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547577
               #:name           "Cincinnati Bengals at Jacksonville Jaguars"
               #:short-name     "CIN @ JAX"
               #:year           2023
               #:week           12
               #:time           (secs->gametime 1701742500)
               #:home           'JAX
               #:away           'CIN
)
 2023 13)

