(define-module (bad-cat nfldb data sched year-2023 week-15)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547593
               #:name           "Los Angeles Chargers at Las Vegas Raiders"
               #:short-name     "LAC @ LV"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702606500)
               #:home           'LV
               #:away           'LAC
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547604
               #:name           "Minnesota Vikings at Cincinnati Bengals"
               #:short-name     "MIN @ CIN"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702753200)
               #:home           'CIN
               #:away           'MIN
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547607
               #:name           "Pittsburgh Steelers at Indianapolis Colts"
               #:short-name     "PIT @ IND"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702765800)
               #:home           'IND
               #:away           'PIT
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547606
               #:name           "Denver Broncos at Detroit Lions"
               #:short-name     "DEN @ DET"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702779300)
               #:home           'DET
               #:away           'DEN
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547605
               #:name           "Chicago Bears at Cleveland Browns"
               #:short-name     "CHI @ CLE"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702839600)
               #:home           'CLE
               #:away           'CHI
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547598
               #:name           "Tampa Bay Buccaneers at Green Bay Packers"
               #:short-name     "TB @ GB"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702839600)
               #:home           'GB
               #:away           'TB
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547595
               #:name           "Houston Texans at Tennessee Titans"
               #:short-name     "HOU @ TEN"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702839600)
               #:home           'TEN
               #:away           'HOU
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547594
               #:name           "New York Jets at Miami Dolphins"
               #:short-name     "NYJ @ MIA"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702839600)
               #:home           'MIA
               #:away           'NYJ
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547608
               #:name           "Kansas City Chiefs at New England Patriots"
               #:short-name     "KC @ NE"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702839600)
               #:home           'NE
               #:away           'KC
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547599
               #:name           "New York Giants at New Orleans Saints"
               #:short-name     "NYG @ NO"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702839600)
               #:home           'NO
               #:away           'NYG
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547603
               #:name           "Atlanta Falcons at Carolina Panthers"
               #:short-name     "ATL @ CAR"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702839600)
               #:home           'CAR
               #:away           'ATL
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547597
               #:name           "Washington Commanders at Los Angeles Rams"
               #:short-name     "WSH @ LAR"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702850700)
               #:home           'LAR
               #:away           'WSH
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547596
               #:name           "San Francisco 49ers at Arizona Cardinals"
               #:short-name     "SF @ ARI"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702850700)
               #:home           'ARI
               #:away           'SF
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547600
               #:name           "Dallas Cowboys at Buffalo Bills"
               #:short-name     "DAL @ BUF"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702851900)
               #:home           'BUF
               #:away           'DAL
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547602
               #:name           "Baltimore Ravens at Jacksonville Jaguars"
               #:short-name     "BAL @ JAX"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702866000)
               #:home           'JAX
               #:away           'BAL
)
 2023 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547601
               #:name           "Philadelphia Eagles at Seattle Seahawks"
               #:short-name     "PHI @ SEA"
               #:year           2023
               #:week           14
               #:time           (secs->gametime 1702952100)
               #:home           'SEA
               #:away           'PHI
)
 2023 15)

