(define-module (bad-cat nfldb data sched year-2023 week-06)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547469
               #:name           "Denver Broncos at Kansas City Chiefs"
               #:short-name     "DEN @ KC"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697156100)
               #:home           'KC
               #:away           'DEN
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547229
               #:name           "Baltimore Ravens at Tennessee Titans"
               #:short-name     "BAL VS TEN"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697376600)
               #:home           'TEN
               #:away           'BAL
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547470
               #:name           "Washington Commanders at Atlanta Falcons"
               #:short-name     "WSH @ ATL"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697389200)
               #:home           'ATL
               #:away           'WSH
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547475
               #:name           "Minnesota Vikings at Chicago Bears"
               #:short-name     "MIN @ CHI"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697389200)
               #:home           'CHI
               #:away           'MIN
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547471
               #:name           "Seattle Seahawks at Cincinnati Bengals"
               #:short-name     "SEA @ CIN"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697389200)
               #:home           'CIN
               #:away           'SEA
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547476
               #:name           "San Francisco 49ers at Cleveland Browns"
               #:short-name     "SF @ CLE"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697389200)
               #:home           'CLE
               #:away           'SF
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547473
               #:name           "Carolina Panthers at Miami Dolphins"
               #:short-name     "CAR @ MIA"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697389200)
               #:home           'MIA
               #:away           'CAR
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547472
               #:name           "Indianapolis Colts at Jacksonville Jaguars"
               #:short-name     "IND @ JAX"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697389200)
               #:home           'JAX
               #:away           'IND
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547477
               #:name           "New Orleans Saints at Houston Texans"
               #:short-name     "NO @ HOU"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697389200)
               #:home           'HOU
               #:away           'NO
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547474
               #:name           "New England Patriots at Las Vegas Raiders"
               #:short-name     "NE @ LV"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697400300)
               #:home           'LV
               #:away           'NE
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547479
               #:name           "Arizona Cardinals at Los Angeles Rams"
               #:short-name     "ARI @ LAR"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697401500)
               #:home           'LAR
               #:away           'ARI
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547480
               #:name           "Philadelphia Eagles at New York Jets"
               #:short-name     "PHI @ NYJ"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697401500)
               #:home           'NYJ
               #:away           'PHI
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547478
               #:name           "Detroit Lions at Tampa Bay Buccaneers"
               #:short-name     "DET @ TB"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697401500)
               #:home           'TB
               #:away           'DET
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547481
               #:name           "New York Giants at Buffalo Bills"
               #:short-name     "NYG @ BUF"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697415600)
               #:home           'BUF
               #:away           'NYG
)
 2023 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547482
               #:name           "Dallas Cowboys at Los Angeles Chargers"
               #:short-name     "DAL @ LAC"
               #:year           2023
               #:week           5
               #:time           (secs->gametime 1697501700)
               #:home           'LAC
               #:away           'DAL
)
 2023 6)

