(define-module (bad-cat nfldb data sched year-2023 week-10)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547525
               #:name           "Carolina Panthers at Chicago Bears"
               #:short-name     "CAR @ CHI"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699582500)
               #:home           'CHI
               #:away           'CAR
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547231
               #:name           "Indianapolis Colts at New England Patriots"
               #:short-name     "IND VS NE"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699803000)
               #:home           'NE
               #:away           'IND
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547526
               #:name           "Houston Texans at Cincinnati Bengals"
               #:short-name     "HOU @ CIN"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699815600)
               #:home           'CIN
               #:away           'HOU
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547533
               #:name           "New Orleans Saints at Minnesota Vikings"
               #:short-name     "NO @ MIN"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699815600)
               #:home           'MIN
               #:away           'NO
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547527
               #:name           "Green Bay Packers at Pittsburgh Steelers"
               #:short-name     "GB @ PIT"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699815600)
               #:home           'PIT
               #:away           'GB
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547528
               #:name           "Tennessee Titans at Tampa Bay Buccaneers"
               #:short-name     "TEN @ TB"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699815600)
               #:home           'TB
               #:away           'TEN
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547532
               #:name           "San Francisco 49ers at Jacksonville Jaguars"
               #:short-name     "SF @ JAX"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699815600)
               #:home           'JAX
               #:away           'SF
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547531
               #:name           "Cleveland Browns at Baltimore Ravens"
               #:short-name     "CLE @ BAL"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699815600)
               #:home           'BAL
               #:away           'CLE
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547529
               #:name           "Atlanta Falcons at Arizona Cardinals"
               #:short-name     "ATL @ ARI"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699826700)
               #:home           'ARI
               #:away           'ATL
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547530
               #:name           "Detroit Lions at Los Angeles Chargers"
               #:short-name     "DET @ LAC"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699826700)
               #:home           'LAC
               #:away           'DET
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547534
               #:name           "New York Giants at Dallas Cowboys"
               #:short-name     "NYG @ DAL"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699827900)
               #:home           'DAL
               #:away           'NYG
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547535
               #:name           "Washington Commanders at Seattle Seahawks"
               #:short-name     "WSH @ SEA"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699827900)
               #:home           'SEA
               #:away           'WSH
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547536
               #:name           "New York Jets at Las Vegas Raiders"
               #:short-name     "NYJ @ LV"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699842000)
               #:home           'LV
               #:away           'NYJ
)
 2023 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547537
               #:name           "Denver Broncos at Buffalo Bills"
               #:short-name     "DEN @ BUF"
               #:year           2023
               #:week           9
               #:time           (secs->gametime 1699928100)
               #:home           'BUF
               #:away           'DEN
)
 2023 10)

