(define-module (bad-cat nfldb data sched year-2023 week-03)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547426
               #:name           "New York Giants at San Francisco 49ers"
               #:short-name     "NYG @ SF"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695341700)
               #:home           'SF
               #:away           'NYG
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547428
               #:name           "Tennessee Titans at Cleveland Browns"
               #:short-name     "TEN @ CLE"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'CLE
               #:away           'TEN
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547433
               #:name           "Atlanta Falcons at Detroit Lions"
               #:short-name     "ATL @ DET"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'DET
               #:away           'ATL
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547434
               #:name           "New Orleans Saints at Green Bay Packers"
               #:short-name     "NO @ GB"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'GB
               #:away           'NO
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547429
               #:name           "Denver Broncos at Miami Dolphins"
               #:short-name     "DEN @ MIA"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'MIA
               #:away           'DEN
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547436
               #:name           "Los Angeles Chargers at Minnesota Vikings"
               #:short-name     "LAC @ MIN"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'MIN
               #:away           'LAC
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547430
               #:name           "New England Patriots at New York Jets"
               #:short-name     "NE @ NYJ"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'NYJ
               #:away           'NE
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547431
               #:name           "Buffalo Bills at Washington Commanders"
               #:short-name     "BUF @ WSH"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'WSH
               #:away           'BUF
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547435
               #:name           "Houston Texans at Jacksonville Jaguars"
               #:short-name     "HOU @ JAX"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'JAX
               #:away           'HOU
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547427
               #:name           "Indianapolis Colts at Baltimore Ravens"
               #:short-name     "IND @ BAL"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695574800)
               #:home           'BAL
               #:away           'IND
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547432
               #:name           "Carolina Panthers at Seattle Seahawks"
               #:short-name     "CAR @ SEA"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695585900)
               #:home           'SEA
               #:away           'CAR
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547438
               #:name           "Chicago Bears at Kansas City Chiefs"
               #:short-name     "CHI @ KC"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695587100)
               #:home           'KC
               #:away           'CHI
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547437
               #:name           "Dallas Cowboys at Arizona Cardinals"
               #:short-name     "DAL @ ARI"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695587100)
               #:home           'ARI
               #:away           'DAL
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547439
               #:name           "Pittsburgh Steelers at Las Vegas Raiders"
               #:short-name     "PIT @ LV"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695601200)
               #:home           'LV
               #:away           'PIT
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547440
               #:name           "Philadelphia Eagles at Tampa Bay Buccaneers"
               #:short-name     "PHI @ TB"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695683700)
               #:home           'TB
               #:away           'PHI
)
 2023 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547441
               #:name           "Los Angeles Rams at Cincinnati Bengals"
               #:short-name     "LAR @ CIN"
               #:year           2023
               #:week           2
               #:time           (secs->gametime 1695687300)
               #:home           'CIN
               #:away           'LAR
)
 2023 3)

