(define-module (bad-cat nfldb data sched year-2023 week-04)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547442
               #:name           "Detroit Lions at Green Bay Packers"
               #:short-name     "DET @ GB"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1695946500)
               #:home           'GB
               #:away           'DET
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547227
               #:name           "Atlanta Falcons at Jacksonville Jaguars"
               #:short-name     "ATL VS JAX"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696167000)
               #:home           'JAX
               #:away           'ATL
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547443
               #:name           "Miami Dolphins at Buffalo Bills"
               #:short-name     "MIA @ BUF"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'BUF
               #:away           'MIA
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547444
               #:name           "Denver Broncos at Chicago Bears"
               #:short-name     "DEN @ CHI"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'CHI
               #:away           'DEN
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547445
               #:name           "Baltimore Ravens at Cleveland Browns"
               #:short-name     "BAL @ CLE"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'CLE
               #:away           'BAL
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547452
               #:name           "Cincinnati Bengals at Tennessee Titans"
               #:short-name     "CIN @ TEN"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'TEN
               #:away           'CIN
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547449
               #:name           "Los Angeles Rams at Indianapolis Colts"
               #:short-name     "LAR @ IND"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'IND
               #:away           'LAR
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547450
               #:name           "Tampa Bay Buccaneers at New Orleans Saints"
               #:short-name     "TB @ NO"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'NO
               #:away           'TB
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547451
               #:name           "Washington Commanders at Philadelphia Eagles"
               #:short-name     "WSH @ PHI"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'PHI
               #:away           'WSH
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547448
               #:name           "Minnesota Vikings at Carolina Panthers"
               #:short-name     "MIN @ CAR"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'CAR
               #:away           'MIN
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547446
               #:name           "Pittsburgh Steelers at Houston Texans"
               #:short-name     "PIT @ HOU"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696179600)
               #:home           'HOU
               #:away           'PIT
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547447
               #:name           "Las Vegas Raiders at Los Angeles Chargers"
               #:short-name     "LV @ LAC"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696190700)
               #:home           'LAC
               #:away           'LV
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547453
               #:name           "New England Patriots at Dallas Cowboys"
               #:short-name     "NE @ DAL"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696191900)
               #:home           'DAL
               #:away           'NE
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547454
               #:name           "Arizona Cardinals at San Francisco 49ers"
               #:short-name     "ARI @ SF"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696191900)
               #:home           'SF
               #:away           'ARI
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547455
               #:name           "Kansas City Chiefs at New York Jets"
               #:short-name     "KC @ NYJ"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696206000)
               #:home           'NYJ
               #:away           'KC
)
 2023 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547456
               #:name           "Seattle Seahawks at New York Giants"
               #:short-name     "SEA @ NYG"
               #:year           2023
               #:week           3
               #:time           (secs->gametime 1696292100)
               #:home           'NYG
               #:away           'SEA
)
 2023 4)

