(define-module (bad-cat nfldb data sched year-2023 week-01)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547353
               #:name           "Detroit Lions at Kansas City Chiefs"
               #:short-name     "DET @ KC"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694132400)
               #:home           'KC
               #:away           'DET
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547403
               #:name           "Carolina Panthers at Atlanta Falcons"
               #:short-name     "CAR @ ATL"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'ATL
               #:away           'CAR
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547397
               #:name           "Cincinnati Bengals at Cleveland Browns"
               #:short-name     "CIN @ CLE"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'CLE
               #:away           'CIN
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547404
               #:name           "Jacksonville Jaguars at Indianapolis Colts"
               #:short-name     "JAX @ IND"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'IND
               #:away           'JAX
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547398
               #:name           "Tampa Bay Buccaneers at Minnesota Vikings"
               #:short-name     "TB @ MIN"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'MIN
               #:away           'TB
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547399
               #:name           "Tennessee Titans at New Orleans Saints"
               #:short-name     "TEN @ NO"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'NO
               #:away           'TEN
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547405
               #:name           "San Francisco 49ers at Pittsburgh Steelers"
               #:short-name     "SF @ PIT"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'PIT
               #:away           'SF
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547406
               #:name           "Arizona Cardinals at Washington Commanders"
               #:short-name     "ARI @ WSH"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'WSH
               #:away           'ARI
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547396
               #:name           "Houston Texans at Baltimore Ravens"
               #:short-name     "HOU @ BAL"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694365200)
               #:home           'BAL
               #:away           'HOU
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547407
               #:name           "Green Bay Packers at Chicago Bears"
               #:short-name     "GB @ CHI"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694377500)
               #:home           'CHI
               #:away           'GB
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547400
               #:name           "Las Vegas Raiders at Denver Broncos"
               #:short-name     "LV @ DEN"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694377500)
               #:home           'DEN
               #:away           'LV
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547402
               #:name           "Philadelphia Eagles at New England Patriots"
               #:short-name     "PHI @ NE"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694377500)
               #:home           'NE
               #:away           'PHI
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547401
               #:name           "Miami Dolphins at Los Angeles Chargers"
               #:short-name     "MIA @ LAC"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694377500)
               #:home           'LAC
               #:away           'MIA
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547408
               #:name           "Los Angeles Rams at Seattle Seahawks"
               #:short-name     "LAR @ SEA"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694377500)
               #:home           'SEA
               #:away           'LAR
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547409
               #:name           "Dallas Cowboys at New York Giants"
               #:short-name     "DAL @ NYG"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694391600)
               #:home           'NYG
               #:away           'DAL
)
 2023 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547352
               #:name           "Buffalo Bills at New York Jets"
               #:short-name     "BUF @ NYJ"
               #:year           2023
               #:week           0
               #:time           (secs->gametime 1694477700)
               #:home           'NYJ
               #:away           'BUF
)
 2023 1)

