(define-module (bad-cat nfldb data sched year-2023 week-14)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547578
               #:name           "New England Patriots at Pittsburgh Steelers"
               #:short-name     "NE @ PIT"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702001700)
               #:home           'PIT
               #:away           'NE
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547579
               #:name           "Tampa Bay Buccaneers at Atlanta Falcons"
               #:short-name     "TB @ ATL"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702234800)
               #:home           'ATL
               #:away           'TB
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547586
               #:name           "Detroit Lions at Chicago Bears"
               #:short-name     "DET @ CHI"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702234800)
               #:home           'CHI
               #:away           'DET
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547580
               #:name           "Indianapolis Colts at Cincinnati Bengals"
               #:short-name     "IND @ CIN"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702234800)
               #:home           'CIN
               #:away           'IND
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547581
               #:name           "Jacksonville Jaguars at Cleveland Browns"
               #:short-name     "JAX @ CLE"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702234800)
               #:home           'CLE
               #:away           'JAX
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547587
               #:name           "Carolina Panthers at New Orleans Saints"
               #:short-name     "CAR @ NO"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702234800)
               #:home           'NO
               #:away           'CAR
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547582
               #:name           "Houston Texans at New York Jets"
               #:short-name     "HOU @ NYJ"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702234800)
               #:home           'NYJ
               #:away           'HOU
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547585
               #:name           "Los Angeles Rams at Baltimore Ravens"
               #:short-name     "LAR @ BAL"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702234800)
               #:home           'BAL
               #:away           'LAR
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547588
               #:name           "Minnesota Vikings at Las Vegas Raiders"
               #:short-name     "MIN @ LV"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702245900)
               #:home           'LV
               #:away           'MIN
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547589
               #:name           "Seattle Seahawks at San Francisco 49ers"
               #:short-name     "SEA @ SF"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702245900)
               #:home           'SF
               #:away           'SEA
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547583
               #:name           "Buffalo Bills at Kansas City Chiefs"
               #:short-name     "BUF @ KC"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702247100)
               #:home           'KC
               #:away           'BUF
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547584
               #:name           "Denver Broncos at Los Angeles Chargers"
               #:short-name     "DEN @ LAC"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702247100)
               #:home           'LAC
               #:away           'DEN
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547590
               #:name           "Philadelphia Eagles at Dallas Cowboys"
               #:short-name     "PHI @ DAL"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702261200)
               #:home           'DAL
               #:away           'PHI
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547592
               #:name           "Tennessee Titans at Miami Dolphins"
               #:short-name     "TEN @ MIA"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702347300)
               #:home           'MIA
               #:away           'TEN
)
 2023 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547591
               #:name           "Green Bay Packers at New York Giants"
               #:short-name     "GB @ NYG"
               #:year           2023
               #:week           13
               #:time           (secs->gametime 1702347300)
               #:home           'NYG
               #:away           'GB
)
 2023 14)

