(define-module (bad-cat nfldb data sched year-2023 week-11)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547538
               #:name           "Cincinnati Bengals at Baltimore Ravens"
               #:short-name     "CIN @ BAL"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700187300)
               #:home           'BAL
               #:away           'CIN
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547539
               #:name           "Pittsburgh Steelers at Cleveland Browns"
               #:short-name     "PIT @ CLE"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'CLE
               #:away           'PIT
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547546
               #:name           "Chicago Bears at Detroit Lions"
               #:short-name     "CHI @ DET"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'DET
               #:away           'CHI
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547547
               #:name           "Los Angeles Chargers at Green Bay Packers"
               #:short-name     "LAC @ GB"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'GB
               #:away           'LAC
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547542
               #:name           "Las Vegas Raiders at Miami Dolphins"
               #:short-name     "LV @ MIA"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'MIA
               #:away           'LV
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547548
               #:name           "New York Giants at Washington Commanders"
               #:short-name     "NYG @ WSH"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'WSH
               #:away           'NYG
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547545
               #:name           "Dallas Cowboys at Carolina Panthers"
               #:short-name     "DAL @ CAR"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'CAR
               #:away           'DAL
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547541
               #:name           "Tennessee Titans at Jacksonville Jaguars"
               #:short-name     "TEN @ JAX"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'JAX
               #:away           'TEN
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547540
               #:name           "Arizona Cardinals at Houston Texans"
               #:short-name     "ARI @ HOU"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700420400)
               #:home           'HOU
               #:away           'ARI
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547549
               #:name           "Tampa Bay Buccaneers at San Francisco 49ers"
               #:short-name     "TB @ SF"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700431500)
               #:home           'SF
               #:away           'TB
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547543
               #:name           "New York Jets at Buffalo Bills"
               #:short-name     "NYJ @ BUF"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700432700)
               #:home           'BUF
               #:away           'NYJ
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547544
               #:name           "Seattle Seahawks at Los Angeles Rams"
               #:short-name     "SEA @ LAR"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700432700)
               #:home           'LAR
               #:away           'SEA
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547550
               #:name           "Minnesota Vikings at Denver Broncos"
               #:short-name     "MIN @ DEN"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700446800)
               #:home           'DEN
               #:away           'MIN
)
 2023 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547345
               #:name           "Philadelphia Eagles at Kansas City Chiefs"
               #:short-name     "PHI @ KC"
               #:year           2023
               #:week           10
               #:time           (secs->gametime 1700532900)
               #:home           'KC
               #:away           'PHI
)
 2023 11)

