(define-module (bad-cat nfldb data sched year-2023 week-18)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547639
               #:name           "Pittsburgh Steelers at Baltimore Ravens"
               #:short-name     "PIT @ BAL"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704580200)
               #:home           'BAL
               #:away           'PIT
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547644
               #:name           "Houston Texans at Indianapolis Colts"
               #:short-name     "HOU @ IND"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704593700)
               #:home           'IND
               #:away           'HOU
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547641
               #:name           "Cleveland Browns at Cincinnati Bengals"
               #:short-name     "CLE @ CIN"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704654000)
               #:home           'CIN
               #:away           'CLE
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547642
               #:name           "Minnesota Vikings at Detroit Lions"
               #:short-name     "MIN @ DET"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704654000)
               #:home           'DET
               #:away           'MIN
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547652
               #:name           "Jacksonville Jaguars at Tennessee Titans"
               #:short-name     "JAX @ TEN"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704654000)
               #:home           'TEN
               #:away           'JAX
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547648
               #:name           "New York Jets at New England Patriots"
               #:short-name     "NYJ @ NE"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704654000)
               #:home           'NE
               #:away           'NYJ
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547649
               #:name           "Atlanta Falcons at New Orleans Saints"
               #:short-name     "ATL @ NO"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704654000)
               #:home           'NO
               #:away           'ATL
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547640
               #:name           "Tampa Bay Buccaneers at Carolina Panthers"
               #:short-name     "TB @ CAR"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704654000)
               #:home           'CAR
               #:away           'TB
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547643
               #:name           "Chicago Bears at Green Bay Packers"
               #:short-name     "CHI @ GB"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704666300)
               #:home           'GB
               #:away           'CHI
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547646
               #:name           "Denver Broncos at Las Vegas Raiders"
               #:short-name     "DEN @ LV"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704666300)
               #:home           'LV
               #:away           'DEN
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547650
               #:name           "Philadelphia Eagles at New York Giants"
               #:short-name     "PHI @ NYG"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704666300)
               #:home           'NYG
               #:away           'PHI
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547638
               #:name           "Seattle Seahawks at Arizona Cardinals"
               #:short-name     "SEA @ ARI"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704666300)
               #:home           'ARI
               #:away           'SEA
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547645
               #:name           "Kansas City Chiefs at Los Angeles Chargers"
               #:short-name     "KC @ LAC"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704666300)
               #:home           'LAC
               #:away           'KC
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547651
               #:name           "Los Angeles Rams at San Francisco 49ers"
               #:short-name     "LAR @ SF"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704666300)
               #:home           'SF
               #:away           'LAR
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547653
               #:name           "Dallas Cowboys at Washington Commanders"
               #:short-name     "DAL @ WSH"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704666300)
               #:home           'WSH
               #:away           'DAL
)
 2023 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547647
               #:name           "Buffalo Bills at Miami Dolphins"
               #:short-name     "BUF @ MIA"
               #:year           2023
               #:week           17
               #:time           (secs->gametime 1704680400)
               #:home           'MIA
               #:away           'BUF
)
 2023 18)

