(define-module (bad-cat nfldb data sched year-2023 week-05)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547457
               #:name           "Chicago Bears at Washington Commanders"
               #:short-name     "CHI @ WSH"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696551300)
               #:home           'WSH
               #:away           'CHI
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547228
               #:name           "Jacksonville Jaguars at Buffalo Bills"
               #:short-name     "JAX VS BUF"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696771800)
               #:home           'BUF
               #:away           'JAX
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547463
               #:name           "Houston Texans at Atlanta Falcons"
               #:short-name     "HOU @ ATL"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696784400)
               #:home           'ATL
               #:away           'HOU
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547464
               #:name           "Carolina Panthers at Detroit Lions"
               #:short-name     "CAR @ DET"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696784400)
               #:home           'DET
               #:away           'CAR
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547458
               #:name           "Tennessee Titans at Indianapolis Colts"
               #:short-name     "TEN @ IND"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696784400)
               #:home           'IND
               #:away           'TEN
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547465
               #:name           "New York Giants at Miami Dolphins"
               #:short-name     "NYG @ MIA"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696784400)
               #:home           'MIA
               #:away           'NYG
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547459
               #:name           "New Orleans Saints at New England Patriots"
               #:short-name     "NO @ NE"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696784400)
               #:home           'NE
               #:away           'NO
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547460
               #:name           "Baltimore Ravens at Pittsburgh Steelers"
               #:short-name     "BAL @ PIT"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696784400)
               #:home           'PIT
               #:away           'BAL
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547467
               #:name           "Philadelphia Eagles at Los Angeles Rams"
               #:short-name     "PHI @ LAR"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696795500)
               #:home           'LAR
               #:away           'PHI
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547466
               #:name           "Cincinnati Bengals at Arizona Cardinals"
               #:short-name     "CIN @ ARI"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696795500)
               #:home           'ARI
               #:away           'CIN
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547461
               #:name           "New York Jets at Denver Broncos"
               #:short-name     "NYJ @ DEN"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696796700)
               #:home           'DEN
               #:away           'NYJ
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547462
               #:name           "Kansas City Chiefs at Minnesota Vikings"
               #:short-name     "KC @ MIN"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696796700)
               #:home           'MIN
               #:away           'KC
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547354
               #:name           "Dallas Cowboys at San Francisco 49ers"
               #:short-name     "DAL @ SF"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696810800)
               #:home           'SF
               #:away           'DAL
)
 2023 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401547468
               #:name           "Green Bay Packers at Las Vegas Raiders"
               #:short-name     "GB @ LV"
               #:year           2023
               #:week           4
               #:time           (secs->gametime 1696896900)
               #:home           'LV
               #:away           'GB
)
 2023 5)

