(define-module (bad-cat nfldb data league)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-teams-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded

 #:use-module (oop goops)
 #:use-module (bad-cat nfldb team)
)

;; AFC NORTH

(make-instance <nfl-team>
               #:id             23
               #:nick           'PIT
               #:name           "Steelers"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              46610
)

)


(make-instance <nfl-team>
               #:id             5
               #:nick           'CLE
               #:name           "Browns"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              71
               #:g              42
               #:b              10760
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              60
               #:b              15360
)

)


(make-instance <nfl-team>
               #:id             4
               #:nick           'CIN
               #:name           "Bengals"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              251
               #:g              79
               #:b              20244
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             33
               #:nick           'BAL
               #:name           "Ravens"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              41
               #:g              18
               #:b              4719
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


;; AFC SOUTH

(make-instance <nfl-team>
               #:id             10
               #:nick           'TEN
               #:name           "Titans"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              75
               #:g              146
               #:b              37595
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              10844
)

)


(make-instance <nfl-team>
               #:id             30
               #:nick           'JAX
               #:name           "Jaguars"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              116
               #:b              29831
)

               #:alt-color      (make-instance <rgb-color>
               #:r              215
               #:g              162
               #:b              41514
)

)


(make-instance <nfl-team>
               #:id             11
               #:nick           'IND
               #:name           "Colts"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              59
               #:b              15221
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              255
               #:b              65535
)

)


(make-instance <nfl-team>
               #:id             34
               #:nick           'HOU
               #:name           "Texans"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              20
               #:b              5183
)

               #:alt-color      (make-instance <rgb-color>
               #:r              196
               #:g              18
               #:b              4656
)

)


;; AFC EAST

(make-instance <nfl-team>
               #:id             20
               #:nick           'NYJ
               #:name           "Jets"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              17
               #:g              87
               #:b              22336
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              255
               #:b              65535
)

)


(make-instance <nfl-team>
               #:id             17
               #:nick           'NE
               #:name           "Patriots"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              10844
)

               #:alt-color      (make-instance <rgb-color>
               #:r              198
               #:g              12
               #:b              3120
)

)


(make-instance <nfl-team>
               #:id             15
               #:nick           'MIA
               #:name           "Dolphins"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              142
               #:b              36503
)

               #:alt-color      (make-instance <rgb-color>
               #:r              252
               #:g              76
               #:b              19458
)

)


(make-instance <nfl-team>
               #:id             2
               #:nick           'BUF
               #:name           "Bills"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              51
               #:b              13197
)

               #:alt-color      (make-instance <rgb-color>
               #:r              213
               #:g              10
               #:b              2570
)

)


;; AFC WEST

(make-instance <nfl-team>
               #:id             13
               #:nick           'LV
               #:name           "Raiders"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

               #:alt-color      (make-instance <rgb-color>
               #:r              165
               #:g              172
               #:b              44207
)

)


(make-instance <nfl-team>
               #:id             24
               #:nick           'LAC
               #:name           "Chargers"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              128
               #:b              32966
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              194
               #:b              49678
)

)


(make-instance <nfl-team>
               #:id             12
               #:nick           'KC
               #:name           "Chiefs"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              227
               #:g              24
               #:b              6199
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              46610
)

)


(make-instance <nfl-team>
               #:id             7
               #:nick           'DEN
               #:name           "Broncos"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              10
               #:g              35
               #:b              9027
)

               #:alt-color      (make-instance <rgb-color>
               #:r              252
               #:g              76
               #:b              19458
)

)


;; NFC NORTH

(make-instance <nfl-team>
               #:id             16
               #:nick           'MIN
               #:name           "Vikings"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              79
               #:g              38
               #:b              9859
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              198
               #:b              50735
)

)


(make-instance <nfl-team>
               #:id             9
               #:nick           'GB
               #:name           "Packers"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              32
               #:g              78
               #:b              20018
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              46610
)

)


(make-instance <nfl-team>
               #:id             8
               #:nick           'DET
               #:name           "Lions"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              118
               #:b              30390
)

               #:alt-color      (make-instance <rgb-color>
               #:r              187
               #:g              187
               #:b              48059
)

)


(make-instance <nfl-team>
               #:id             3
               #:nick           'CHI
               #:name           "Bears"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              11
               #:g              28
               #:b              7226
)

               #:alt-color      (make-instance <rgb-color>
               #:r              230
               #:g              65
               #:b              16640
)

)


;; NFC SOUTH

(make-instance <nfl-team>
               #:id             27
               #:nick           'TB
               #:name           "Buccaneers"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              189
               #:g              28
               #:b              7222
)

               #:alt-color      (make-instance <rgb-color>
               #:r              62
               #:g              58
               #:b              14901
)

)


(make-instance <nfl-team>
               #:id             18
               #:nick           'NO
               #:name           "Saints"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              211
               #:g              188
               #:b              48269
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             29
               #:nick           'CAR
               #:name           "Panthers"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              133
               #:b              34250
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             1
               #:nick           'ATL
               #:name           "Falcons"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              167
               #:g              25
               #:b              6448
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


;; NFC EAST

(make-instance <nfl-team>
               #:id             28
               #:nick           'WSH
               #:name           "Commanders"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              90
               #:g              20
               #:b              5140
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              46610
)

)


(make-instance <nfl-team>
               #:id             21
               #:nick           'PHI
               #:name           "Eagles"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              6
               #:g              66
               #:b              16973
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             19
               #:nick           'NYG
               #:name           "Giants"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              60
               #:b              15487
)

               #:alt-color      (make-instance <rgb-color>
               #:r              201
               #:g              36
               #:b              9279
)

)


(make-instance <nfl-team>
               #:id             6
               #:nick           'DAL
               #:name           "Cowboys"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              10844
)

               #:alt-color      (make-instance <rgb-color>
               #:r              176
               #:g              183
               #:b              47036
)

)


;; NFC WEST

(make-instance <nfl-team>
               #:id             25
               #:nick           'SF
               #:name           "49ers"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              170
               #:g              0
               #:b              0
)

               #:alt-color      (make-instance <rgb-color>
               #:r              179
               #:g              153
               #:b              39261
)

)


(make-instance <nfl-team>
               #:id             26
               #:nick           'SEA
               #:name           "Seahawks"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              10844
)

               #:alt-color      (make-instance <rgb-color>
               #:r              105
               #:g              190
               #:b              48680
)

)


(make-instance <nfl-team>
               #:id             14
               #:nick           'LAR
               #:name           "Rams"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              53
               #:b              13716
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              209
               #:b              53504
)

)


(make-instance <nfl-team>
               #:id             22
               #:nick           'ARI
               #:name           "Cardinals"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              164
               #:g              2
               #:b              551
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              255
               #:b              65535
)

)


