 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-teams-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded

;; AFC NORTH

(make-instance <nfl-team>
               #:id             23
               #:nick           'PIT
               #:name           "Steelers"
               #:display-name   "Pittsburgh Steelers"
               #:location       "Pittsburgh"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              18
)

)


(make-instance <nfl-team>
               #:id             5
               #:nick           'CLE
               #:name           "Browns"
               #:display-name   "Cleveland Browns"
               #:location       "Cleveland"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              71
               #:g              42
               #:b              8
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              60
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             4
               #:nick           'CIN
               #:name           "Bengals"
               #:display-name   "Cincinnati Bengals"
               #:location       "Cincinnati"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              251
               #:g              79
               #:b              20
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             33
               #:nick           'BAL
               #:name           "Ravens"
               #:display-name   "Baltimore Ravens"
               #:location       "Baltimore"
               #:conf           'AFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              41
               #:g              18
               #:b              111
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


;; AFC SOUTH

(make-instance <nfl-team>
               #:id             10
               #:nick           'TEN
               #:name           "Titans"
               #:display-name   "Tennessee Titans"
               #:location       "Tennessee"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              75
               #:g              146
               #:b              219
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              92
)

)


(make-instance <nfl-team>
               #:id             30
               #:nick           'JAX
               #:name           "Jaguars"
               #:display-name   "Jacksonville Jaguars"
               #:location       "Jacksonville"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              116
               #:b              135
)

               #:alt-color      (make-instance <rgb-color>
               #:r              215
               #:g              162
               #:b              42
)

)


(make-instance <nfl-team>
               #:id             11
               #:nick           'IND
               #:name           "Colts"
               #:display-name   "Indianapolis Colts"
               #:location       "Indianapolis"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              59
               #:b              117
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              255
               #:b              255
)

)


(make-instance <nfl-team>
               #:id             34
               #:nick           'HOU
               #:name           "Texans"
               #:display-name   "Houston Texans"
               #:location       "Houston"
               #:conf           'AFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              20
               #:b              63
)

               #:alt-color      (make-instance <rgb-color>
               #:r              196
               #:g              18
               #:b              48
)

)


;; AFC EAST

(make-instance <nfl-team>
               #:id             20
               #:nick           'NYJ
               #:name           "Jets"
               #:display-name   "New York Jets"
               #:location       "New York"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              17
               #:g              87
               #:b              64
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              255
               #:b              255
)

)


(make-instance <nfl-team>
               #:id             17
               #:nick           'NE
               #:name           "Patriots"
               #:display-name   "New England Patriots"
               #:location       "New England"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              92
)

               #:alt-color      (make-instance <rgb-color>
               #:r              198
               #:g              12
               #:b              48
)

)


(make-instance <nfl-team>
               #:id             15
               #:nick           'MIA
               #:name           "Dolphins"
               #:display-name   "Miami Dolphins"
               #:location       "Miami"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              142
               #:b              151
)

               #:alt-color      (make-instance <rgb-color>
               #:r              252
               #:g              76
               #:b              2
)

)


(make-instance <nfl-team>
               #:id             2
               #:nick           'BUF
               #:name           "Bills"
               #:display-name   "Buffalo Bills"
               #:location       "Buffalo"
               #:conf           'AFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              51
               #:b              141
)

               #:alt-color      (make-instance <rgb-color>
               #:r              213
               #:g              10
               #:b              10
)

)


;; AFC WEST

(make-instance <nfl-team>
               #:id             13
               #:nick           'LV
               #:name           "Raiders"
               #:display-name   "Las Vegas Raiders"
               #:location       "Las Vegas"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

               #:alt-color      (make-instance <rgb-color>
               #:r              165
               #:g              172
               #:b              175
)

)


(make-instance <nfl-team>
               #:id             24
               #:nick           'LAC
               #:name           "Chargers"
               #:display-name   "Los Angeles Chargers"
               #:location       "Los Angeles"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              128
               #:b              198
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              194
               #:b              14
)

)


(make-instance <nfl-team>
               #:id             12
               #:nick           'KC
               #:name           "Chiefs"
               #:display-name   "Kansas City Chiefs"
               #:location       "Kansas City"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              227
               #:g              24
               #:b              55
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              18
)

)


(make-instance <nfl-team>
               #:id             7
               #:nick           'DEN
               #:name           "Broncos"
               #:display-name   "Denver Broncos"
               #:location       "Denver"
               #:conf           'AFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              10
               #:g              35
               #:b              67
)

               #:alt-color      (make-instance <rgb-color>
               #:r              252
               #:g              76
               #:b              2
)

)


;; NFC NORTH

(make-instance <nfl-team>
               #:id             16
               #:nick           'MIN
               #:name           "Vikings"
               #:display-name   "Minnesota Vikings"
               #:location       "Minnesota"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              79
               #:g              38
               #:b              131
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              198
               #:b              47
)

)


(make-instance <nfl-team>
               #:id             9
               #:nick           'GB
               #:name           "Packers"
               #:display-name   "Green Bay Packers"
               #:location       "Green Bay"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              32
               #:g              78
               #:b              50
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              18
)

)


(make-instance <nfl-team>
               #:id             8
               #:nick           'DET
               #:name           "Lions"
               #:display-name   "Detroit Lions"
               #:location       "Detroit"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              118
               #:b              182
)

               #:alt-color      (make-instance <rgb-color>
               #:r              187
               #:g              187
               #:b              187
)

)


(make-instance <nfl-team>
               #:id             3
               #:nick           'CHI
               #:name           "Bears"
               #:display-name   "Chicago Bears"
               #:location       "Chicago"
               #:conf           'NFC
               #:div            'NORTH
               #:color          (make-instance <rgb-color>
               #:r              11
               #:g              28
               #:b              58
)

               #:alt-color      (make-instance <rgb-color>
               #:r              230
               #:g              65
               #:b              0
)

)


;; NFC SOUTH

(make-instance <nfl-team>
               #:id             27
               #:nick           'TB
               #:name           "Buccaneers"
               #:display-name   "Tampa Bay Buccaneers"
               #:location       "Tampa Bay"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              189
               #:g              28
               #:b              54
)

               #:alt-color      (make-instance <rgb-color>
               #:r              62
               #:g              58
               #:b              53
)

)


(make-instance <nfl-team>
               #:id             18
               #:nick           'NO
               #:name           "Saints"
               #:display-name   "New Orleans Saints"
               #:location       "New Orleans"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              211
               #:g              188
               #:b              141
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             29
               #:nick           'CAR
               #:name           "Panthers"
               #:display-name   "Carolina Panthers"
               #:location       "Carolina"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              133
               #:b              202
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             1
               #:nick           'ATL
               #:name           "Falcons"
               #:display-name   "Atlanta Falcons"
               #:location       "Atlanta"
               #:conf           'NFC
               #:div            'SOUTH
               #:color          (make-instance <rgb-color>
               #:r              167
               #:g              25
               #:b              48
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


;; NFC EAST

(make-instance <nfl-team>
               #:id             28
               #:nick           'WSH
               #:name           "Commanders"
               #:display-name   "Washington Commanders"
               #:location       "Washington"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              90
               #:g              20
               #:b              20
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              182
               #:b              18
)

)


(make-instance <nfl-team>
               #:id             21
               #:nick           'PHI
               #:name           "Eagles"
               #:display-name   "Philadelphia Eagles"
               #:location       "Philadelphia"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              6
               #:g              66
               #:b              77
)

               #:alt-color      (make-instance <rgb-color>
               #:r              0
               #:g              0
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             19
               #:nick           'NYG
               #:name           "Giants"
               #:display-name   "New York Giants"
               #:location       "New York"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              60
               #:b              127
)

               #:alt-color      (make-instance <rgb-color>
               #:r              201
               #:g              36
               #:b              63
)

)


(make-instance <nfl-team>
               #:id             6
               #:nick           'DAL
               #:name           "Cowboys"
               #:display-name   "Dallas Cowboys"
               #:location       "Dallas"
               #:conf           'NFC
               #:div            'EAST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              92
)

               #:alt-color      (make-instance <rgb-color>
               #:r              176
               #:g              183
               #:b              188
)

)


;; NFC WEST

(make-instance <nfl-team>
               #:id             25
               #:nick           'SF
               #:name           "49ers"
               #:display-name   "San Francisco 49ers"
               #:location       "San Francisco"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              170
               #:g              0
               #:b              0
)

               #:alt-color      (make-instance <rgb-color>
               #:r              179
               #:g              153
               #:b              93
)

)


(make-instance <nfl-team>
               #:id             26
               #:nick           'SEA
               #:name           "Seahawks"
               #:display-name   "Seattle Seahawks"
               #:location       "Seattle"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              42
               #:b              92
)

               #:alt-color      (make-instance <rgb-color>
               #:r              105
               #:g              190
               #:b              40
)

)


(make-instance <nfl-team>
               #:id             14
               #:nick           'LAR
               #:name           "Rams"
               #:display-name   "Los Angeles Rams"
               #:location       "Los Angeles"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              0
               #:g              53
               #:b              148
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              209
               #:b              0
)

)


(make-instance <nfl-team>
               #:id             22
               #:nick           'ARI
               #:name           "Cardinals"
               #:display-name   "Arizona Cardinals"
               #:location       "Arizona"
               #:conf           'NFC
               #:div            'WEST
               #:color          (make-instance <rgb-color>
               #:r              164
               #:g              2
               #:b              39
)

               #:alt-color      (make-instance <rgb-color>
               #:r              255
               #:g              255
               #:b              255
)

)


