(define-module (bad-cat nfldb data sched year-2024 week-05)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671815
               #:name           "Tampa Bay Buccaneers at Atlanta Falcons"
               #:short-name     "TB @ ATL"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728000900)
               #:home           'ATL
               #:away           'TB
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671804
               #:name           "New York Jets at Minnesota Vikings"
               #:short-name     "NYJ VS MIN"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728221400)
               #:home           'MIN
               #:away           'NYJ
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671872
               #:name           "Carolina Panthers at Chicago Bears"
               #:short-name     "CAR @ CHI"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728234000)
               #:home           'CHI
               #:away           'CAR
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671626
               #:name           "Baltimore Ravens at Cincinnati Bengals"
               #:short-name     "BAL @ CIN"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728234000)
               #:home           'CIN
               #:away           'BAL
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671700
               #:name           "Miami Dolphins at New England Patriots"
               #:short-name     "MIA @ NE"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728234000)
               #:home           'NE
               #:away           'MIA
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671718
               #:name           "Cleveland Browns at Washington Commanders"
               #:short-name     "CLE @ WSH"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728234000)
               #:home           'WSH
               #:away           'CLE
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671633
               #:name           "Indianapolis Colts at Jacksonville Jaguars"
               #:short-name     "IND @ JAX"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728234000)
               #:home           'JAX
               #:away           'IND
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671859
               #:name           "Buffalo Bills at Houston Texans"
               #:short-name     "BUF @ HOU"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728234000)
               #:home           'HOU
               #:away           'BUF
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671747
               #:name           "Las Vegas Raiders at Denver Broncos"
               #:short-name     "LV @ DEN"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728245100)
               #:home           'DEN
               #:away           'LV
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671756
               #:name           "Arizona Cardinals at San Francisco 49ers"
               #:short-name     "ARI @ SF"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728245100)
               #:home           'SF
               #:away           'ARI
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671679
               #:name           "Green Bay Packers at Los Angeles Rams"
               #:short-name     "GB @ LAR"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728246300)
               #:home           'LAR
               #:away           'GB
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671680
               #:name           "New York Giants at Seattle Seahawks"
               #:short-name     "NYG @ SEA"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728246300)
               #:home           'SEA
               #:away           'NYG
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671784
               #:name           "Dallas Cowboys at Pittsburgh Steelers"
               #:short-name     "DAL @ PIT"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728265500)
               #:home           'PIT
               #:away           'DAL
)
 2024 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671687
               #:name           "New Orleans Saints at Kansas City Chiefs"
               #:short-name     "NO @ KC"
               #:year           2024
               #:week           4
               #:time           (secs->gametime 1728346500)
               #:home           'KC
               #:away           'NO
)
 2024 5)

