(define-module (bad-cat nfldb data sched year-2024 week-09)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671809
               #:name           "Houston Texans at New York Jets"
               #:short-name     "HOU @ NYJ"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730420100)
               #:home           'NYJ
               #:away           'HOU
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671728
               #:name           "Dallas Cowboys at Atlanta Falcons"
               #:short-name     "DAL @ ATL"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'ATL
               #:away           'DAL
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671493
               #:name           "Miami Dolphins at Buffalo Bills"
               #:short-name     "MIA @ BUF"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'BUF
               #:away           'MIA
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671704
               #:name           "Las Vegas Raiders at Cincinnati Bengals"
               #:short-name     "LV @ CIN"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'CIN
               #:away           'LV
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671629
               #:name           "Los Angeles Chargers at Cleveland Browns"
               #:short-name     "LAC @ CLE"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'CLE
               #:away           'LAC
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671822
               #:name           "New England Patriots at Tennessee Titans"
               #:short-name     "NE @ TEN"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'TEN
               #:away           'NE
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671711
               #:name           "Washington Commanders at New York Giants"
               #:short-name     "WSH @ NYG"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'NYG
               #:away           'WSH
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671650
               #:name           "New Orleans Saints at Carolina Panthers"
               #:short-name     "NO @ CAR"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'CAR
               #:away           'NO
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671623
               #:name           "Denver Broncos at Baltimore Ravens"
               #:short-name     "DEN @ BAL"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730660400)
               #:home           'BAL
               #:away           'DEN
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671797
               #:name           "Jacksonville Jaguars at Philadelphia Eagles"
               #:short-name     "JAX @ PHI"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730671500)
               #:home           'PHI
               #:away           'JAX
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671661
               #:name           "Chicago Bears at Arizona Cardinals"
               #:short-name     "CHI @ ARI"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730671500)
               #:home           'ARI
               #:away           'CHI
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671767
               #:name           "Detroit Lions at Green Bay Packers"
               #:short-name     "DET @ GB"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730672700)
               #:home           'GB
               #:away           'DET
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671776
               #:name           "Los Angeles Rams at Seattle Seahawks"
               #:short-name     "LAR @ SEA"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730672700)
               #:home           'SEA
               #:away           'LAR
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671647
               #:name           "Indianapolis Colts at Minnesota Vikings"
               #:short-name     "IND @ MIN"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730686800)
               #:home           'MIN
               #:away           'IND
)
 2024 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671688
               #:name           "Tampa Bay Buccaneers at Kansas City Chiefs"
               #:short-name     "TB @ KC"
               #:year           2024
               #:week           8
               #:time           (secs->gametime 1730772900)
               #:home           'KC
               #:away           'TB
)
 2024 9)

