(define-module (bad-cat nfldb data sched year-2024 week-14)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 13

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671814
               #:name           "Green Bay Packers at Detroit Lions"
               #:short-name     "GB @ DET"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733451300)
               #:home           'DET
               #:away           'GB
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671821
               #:name           "Jacksonville Jaguars at Tennessee Titans"
               #:short-name     "JAX @ TEN"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733684400)
               #:home           'TEN
               #:away           'JAX
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671848
               #:name           "New York Jets at Miami Dolphins"
               #:short-name     "NYJ @ MIA"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733684400)
               #:home           'MIA
               #:away           'NYJ
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671648
               #:name           "Atlanta Falcons at Minnesota Vikings"
               #:short-name     "ATL @ MIN"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733684400)
               #:home           'MIN
               #:away           'ATL
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671601
               #:name           "New Orleans Saints at New York Giants"
               #:short-name     "NO @ NYG"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733684400)
               #:home           'NYG
               #:away           'NO
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671713
               #:name           "Carolina Panthers at Philadelphia Eagles"
               #:short-name     "CAR @ PHI"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733684400)
               #:home           'PHI
               #:away           'CAR
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671631
               #:name           "Cleveland Browns at Pittsburgh Steelers"
               #:short-name     "CLE @ PIT"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733684400)
               #:home           'PIT
               #:away           'CLE
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671654
               #:name           "Las Vegas Raiders at Tampa Bay Buccaneers"
               #:short-name     "LV @ TB"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733684400)
               #:home           'TB
               #:away           'LV
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671660
               #:name           "Seattle Seahawks at Arizona Cardinals"
               #:short-name     "SEA @ ARI"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733695500)
               #:home           'ARI
               #:away           'SEA
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671773
               #:name           "Buffalo Bills at Los Angeles Rams"
               #:short-name     "BUF @ LAR"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733696700)
               #:home           'LAR
               #:away           'BUF
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671774
               #:name           "Chicago Bears at San Francisco 49ers"
               #:short-name     "CHI @ SF"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733696700)
               #:home           'SF
               #:away           'CHI
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671788
               #:name           "Los Angeles Chargers at Kansas City Chiefs"
               #:short-name     "LAC @ KC"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733710800)
               #:home           'KC
               #:away           'LAC
)
 2024 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671690
               #:name           "Cincinnati Bengals at Dallas Cowboys"
               #:short-name     "CIN @ DAL"
               #:year           2024
               #:week           13
               #:time           (secs->gametime 1733796900)
               #:home           'DAL
               #:away           'CIN
)
 2024 14)

