(define-module (bad-cat nfldb data sched year-2024 week-08)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671817
               #:name           "Minnesota Vikings at Los Angeles Rams"
               #:short-name     "MIN @ LAR"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1729815300)
               #:home           'LAR
               #:away           'MIN
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671667
               #:name           "Philadelphia Eagles at Cincinnati Bengals"
               #:short-name     "PHI @ CIN"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'CIN
               #:away           'PHI
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671852
               #:name           "Baltimore Ravens at Cleveland Browns"
               #:short-name     "BAL @ CLE"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'CLE
               #:away           'BAL
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671720
               #:name           "Tennessee Titans at Detroit Lions"
               #:short-name     "TEN @ DET"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'DET
               #:away           'TEN
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671850
               #:name           "Arizona Cardinals at Miami Dolphins"
               #:short-name     "ARI @ MIA"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'MIA
               #:away           'ARI
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671618
               #:name           "New York Jets at New England Patriots"
               #:short-name     "NYJ @ NE"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'NE
               #:away           'NYJ
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671739
               #:name           "Atlanta Falcons at Tampa Bay Buccaneers"
               #:short-name     "ATL @ TB"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'TB
               #:away           'ATL
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671707
               #:name           "Green Bay Packers at Jacksonville Jaguars"
               #:short-name     "GB @ JAX"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'JAX
               #:away           'GB
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671856
               #:name           "Indianapolis Colts at Houston Texans"
               #:short-name     "IND @ HOU"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730048400)
               #:home           'HOU
               #:away           'IND
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671750
               #:name           "New Orleans Saints at Los Angeles Chargers"
               #:short-name     "NO @ LAC"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730059500)
               #:home           'LAC
               #:away           'NO
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671760
               #:name           "Buffalo Bills at Seattle Seahawks"
               #:short-name     "BUF @ SEA"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730059500)
               #:home           'SEA
               #:away           'BUF
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671600
               #:name           "Carolina Panthers at Denver Broncos"
               #:short-name     "CAR @ DEN"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730060700)
               #:home           'DEN
               #:away           'CAR
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671671
               #:name           "Kansas City Chiefs at Las Vegas Raiders"
               #:short-name     "KC @ LV"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730060700)
               #:home           'LV
               #:away           'KC
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671599
               #:name           "Chicago Bears at Washington Commanders"
               #:short-name     "CHI @ WSH"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730060700)
               #:home           'WSH
               #:away           'CHI
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671795
               #:name           "Dallas Cowboys at San Francisco 49ers"
               #:short-name     "DAL @ SF"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730074800)
               #:home           'SF
               #:away           'DAL
)
 2024 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671685
               #:name           "New York Giants at Pittsburgh Steelers"
               #:short-name     "NYG @ PIT"
               #:year           2024
               #:week           7
               #:time           (secs->gametime 1730160900)
               #:home           'PIT
               #:away           'NYG
)
 2024 8)

