(define-module (bad-cat nfldb data sched year-2024 week-04)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671812
               #:name           "Dallas Cowboys at New York Giants"
               #:short-name     "DAL @ NYG"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727396100)
               #:home           'NYG
               #:away           'DAL
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671727
               #:name           "New Orleans Saints at Atlanta Falcons"
               #:short-name     "NO @ ATL"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'ATL
               #:away           'NO
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671871
               #:name           "Los Angeles Rams at Chicago Bears"
               #:short-name     "LAR @ CHI"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'CHI
               #:away           'LAR
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671643
               #:name           "Minnesota Vikings at Green Bay Packers"
               #:short-name     "MIN @ GB"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'GB
               #:away           'MIN
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671867
               #:name           "Pittsburgh Steelers at Indianapolis Colts"
               #:short-name     "PIT @ IND"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'IND
               #:away           'PIT
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671622
               #:name           "Denver Broncos at New York Jets"
               #:short-name     "DEN @ NYJ"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'NYJ
               #:away           'DEN
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671740
               #:name           "Philadelphia Eagles at Tampa Bay Buccaneers"
               #:short-name     "PHI @ TB"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'TB
               #:away           'PHI
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671745
               #:name           "Cincinnati Bengals at Carolina Panthers"
               #:short-name     "CIN @ CAR"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'CAR
               #:away           'CIN
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671857
               #:name           "Jacksonville Jaguars at Houston Texans"
               #:short-name     "JAX @ HOU"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727629200)
               #:home           'HOU
               #:away           'JAX
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671755
               #:name           "Washington Commanders at Arizona Cardinals"
               #:short-name     "WSH @ ARI"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727640300)
               #:home           'ARI
               #:away           'WSH
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671758
               #:name           "New England Patriots at San Francisco 49ers"
               #:short-name     "NE @ SF"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727640300)
               #:home           'SF
               #:away           'NE
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671672
               #:name           "Cleveland Browns at Las Vegas Raiders"
               #:short-name     "CLE @ LV"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727641500)
               #:home           'LV
               #:away           'CLE
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671674
               #:name           "Kansas City Chiefs at Los Angeles Chargers"
               #:short-name     "KC @ LAC"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727641500)
               #:home           'LAC
               #:away           'KC
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671783
               #:name           "Buffalo Bills at Baltimore Ravens"
               #:short-name     "BUF @ BAL"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727655600)
               #:home           'BAL
               #:away           'BUF
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671683
               #:name           "Tennessee Titans at Miami Dolphins"
               #:short-name     "TEN @ MIA"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727739000)
               #:home           'MIA
               #:away           'TEN
)
 2024 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671491
               #:name           "Seattle Seahawks at Detroit Lions"
               #:short-name     "SEA @ DET"
               #:year           2024
               #:week           3
               #:time           (secs->gametime 1727741700)
               #:home           'DET
               #:away           'SEA
)
 2024 4)

