(define-module (bad-cat nfldb data sched year-2024 week-12)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 13

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671875
               #:name           "Pittsburgh Steelers at Cleveland Browns"
               #:short-name     "PIT @ CLE"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732241700)
               #:home           'CLE
               #:away           'PIT
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671870
               #:name           "Minnesota Vikings at Chicago Bears"
               #:short-name     "MIN @ CHI"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732474800)
               #:home           'CHI
               #:away           'MIN
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671866
               #:name           "Detroit Lions at Indianapolis Colts"
               #:short-name     "DET @ IND"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732474800)
               #:home           'IND
               #:away           'DET
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671847
               #:name           "New England Patriots at Miami Dolphins"
               #:short-name     "NE @ MIA"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732474800)
               #:home           'MIA
               #:away           'NE
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671638
               #:name           "Tampa Bay Buccaneers at New York Giants"
               #:short-name     "TB @ NYG"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732474800)
               #:home           'NYG
               #:away           'TB
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671715
               #:name           "Dallas Cowboys at Washington Commanders"
               #:short-name     "DAL @ WSH"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732474800)
               #:home           'WSH
               #:away           'DAL
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671651
               #:name           "Kansas City Chiefs at Carolina Panthers"
               #:short-name     "KC @ CAR"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732474800)
               #:home           'CAR
               #:away           'KC
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671858
               #:name           "Tennessee Titans at Houston Texans"
               #:short-name     "TEN @ HOU"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732474800)
               #:home           'HOU
               #:away           'TEN
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671656
               #:name           "Denver Broncos at Las Vegas Raiders"
               #:short-name     "DEN @ LV"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732485900)
               #:home           'LV
               #:away           'DEN
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671768
               #:name           "San Francisco 49ers at Green Bay Packers"
               #:short-name     "SF @ GB"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732487100)
               #:home           'GB
               #:away           'SF
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671775
               #:name           "Arizona Cardinals at Seattle Seahawks"
               #:short-name     "ARI @ SEA"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732487100)
               #:home           'SEA
               #:away           'ARI
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671794
               #:name           "Philadelphia Eagles at Los Angeles Rams"
               #:short-name     "PHI @ LAR"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732501200)
               #:home           'LAR
               #:away           'PHI
)
 2024 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671689
               #:name           "Baltimore Ravens at Los Angeles Chargers"
               #:short-name     "BAL @ LAC"
               #:year           2024
               #:week           11
               #:time           (secs->gametime 1732587300)
               #:home           'LAC
               #:away           'BAL
)
 2024 12)

