(define-module (bad-cat nfldb data sched year-2024 week-01)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671789
               #:name           "Baltimore Ravens at Kansas City Chiefs"
               #:short-name     "BAL @ KC"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725583200)
               #:home           'KC
               #:away           'BAL
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671805
               #:name           "Green Bay Packers at Philadelphia Eagles"
               #:short-name     "GB VS PHI"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725668100)
               #:home           'PHI
               #:away           'GB
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671744
               #:name           "Pittsburgh Steelers at Atlanta Falcons"
               #:short-name     "PIT @ ATL"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'ATL
               #:away           'PIT
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671617
               #:name           "Arizona Cardinals at Buffalo Bills"
               #:short-name     "ARI @ BUF"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'BUF
               #:away           'ARI
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671719
               #:name           "Tennessee Titans at Chicago Bears"
               #:short-name     "TEN @ CHI"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'CHI
               #:away           'TEN
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671628
               #:name           "New England Patriots at Cincinnati Bengals"
               #:short-name     "NE @ CIN"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'CIN
               #:away           'NE
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671861
               #:name           "Houston Texans at Indianapolis Colts"
               #:short-name     "HOU @ IND"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'IND
               #:away           'HOU
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671849
               #:name           "Jacksonville Jaguars at Miami Dolphins"
               #:short-name     "JAX @ MIA"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'MIA
               #:away           'JAX
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671734
               #:name           "Carolina Panthers at New Orleans Saints"
               #:short-name     "CAR @ NO"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'NO
               #:away           'CAR
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671712
               #:name           "Minnesota Vikings at New York Giants"
               #:short-name     "MIN @ NYG"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725814800)
               #:home           'NYG
               #:away           'MIN
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671659
               #:name           "Las Vegas Raiders at Los Angeles Chargers"
               #:short-name     "LV @ LAC"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725825900)
               #:home           'LAC
               #:away           'LV
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671664
               #:name           "Denver Broncos at Seattle Seahawks"
               #:short-name     "DEN @ SEA"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725825900)
               #:home           'SEA
               #:away           'DEN
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671761
               #:name           "Dallas Cowboys at Cleveland Browns"
               #:short-name     "DAL @ CLE"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725827100)
               #:home           'CLE
               #:away           'DAL
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671770
               #:name           "Washington Commanders at Tampa Bay Buccaneers"
               #:short-name     "WSH @ TB"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725827100)
               #:home           'TB
               #:away           'WSH
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671792
               #:name           "Los Angeles Rams at Detroit Lions"
               #:short-name     "LAR @ DET"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725841200)
               #:home           'DET
               #:away           'LAR
)
 2024 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671696
               #:name           "New York Jets at San Francisco 49ers"
               #:short-name     "NYJ @ SF"
               #:year           2024
               #:week           0
               #:time           (secs->gametime 1725927300)
               #:home           'SF
               #:away           'NYJ
)
 2024 1)

