(define-module (bad-cat nfldb data sched year-2024 week-17)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671799
               #:name           "Kansas City Chiefs at Pittsburgh Steelers"
               #:short-name     "KC @ PIT"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735153200)
               #:home           'PIT
               #:away           'KC
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671800
               #:name           "Baltimore Ravens at Houston Texans"
               #:short-name     "BAL @ HOU"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735165800)
               #:home           'HOU
               #:away           'BAL
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671876
               #:name           "Seattle Seahawks at Chicago Bears"
               #:short-name     "SEA @ CHI"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735265700)
               #:home           'CHI
               #:away           'SEA
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671832
               #:name           "Los Angeles Chargers at New England Patriots"
               #:short-name     "LAC @ NE"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735412400)
               #:home           'NE
               #:away           'LAC
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671835
               #:name           "Denver Broncos at Cincinnati Bengals"
               #:short-name     "DEN @ CIN"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735425000)
               #:home           'CIN
               #:away           'DEN
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671829
               #:name           "Arizona Cardinals at Los Angeles Rams"
               #:short-name     "ARI @ LAR"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735437600)
               #:home           'LAR
               #:away           'ARI
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671495
               #:name           "New York Jets at Buffalo Bills"
               #:short-name     "NYJ @ BUF"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735498800)
               #:home           'BUF
               #:away           'NYJ
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671738
               #:name           "Las Vegas Raiders at New Orleans Saints"
               #:short-name     "LV @ NO"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735498800)
               #:home           'NO
               #:away           'LV
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671846
               #:name           "Indianapolis Colts at New York Giants"
               #:short-name     "IND @ NYG"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735498800)
               #:home           'NYG
               #:away           'IND
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671765
               #:name           "Dallas Cowboys at Philadelphia Eagles"
               #:short-name     "DAL @ PHI"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735498800)
               #:home           'PHI
               #:away           'DAL
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671653
               #:name           "Carolina Panthers at Tampa Bay Buccaneers"
               #:short-name     "CAR @ TB"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735498800)
               #:home           'TB
               #:away           'CAR
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671634
               #:name           "Tennessee Titans at Jacksonville Jaguars"
               #:short-name     "TEN @ JAX"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735498800)
               #:home           'JAX
               #:away           'TEN
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671877
               #:name           "Miami Dolphins at Cleveland Browns"
               #:short-name     "MIA @ CLE"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735509900)
               #:home           'CLE
               #:away           'MIA
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671725
               #:name           "Green Bay Packers at Minnesota Vikings"
               #:short-name     "GB @ MIN"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735511100)
               #:home           'MIN
               #:away           'GB
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671842
               #:name           "Atlanta Falcons at Washington Commanders"
               #:short-name     "ATL @ WSH"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735525200)
               #:home           'WSH
               #:away           'ATL
)
 2024 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671698
               #:name           "Detroit Lions at San Francisco 49ers"
               #:short-name     "DET @ SF"
               #:year           2024
               #:week           16
               #:time           (secs->gametime 1735611300)
               #:home           'SF
               #:away           'DET
)
 2024 17)

