(define-module (bad-cat nfldb data sched year-2024 week-06)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671819
               #:name           "San Francisco 49ers at Seattle Seahawks"
               #:short-name     "SF @ SEA"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728605700)
               #:home           'SEA
               #:away           'SF
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671802
               #:name           "Jacksonville Jaguars at Chicago Bears"
               #:short-name     "JAX VS CHI"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728826200)
               #:home           'CHI
               #:away           'JAX
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671722
               #:name           "Arizona Cardinals at Green Bay Packers"
               #:short-name     "ARI @ GB"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728838800)
               #:home           'GB
               #:away           'ARI
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671820
               #:name           "Indianapolis Colts at Tennessee Titans"
               #:short-name     "IND @ TEN"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728838800)
               #:home           'TEN
               #:away           'IND
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671619
               #:name           "Houston Texans at New England Patriots"
               #:short-name     "HOU @ NE"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728838800)
               #:home           'NE
               #:away           'HOU
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671735
               #:name           "Tampa Bay Buccaneers at New Orleans Saints"
               #:short-name     "TB @ NO"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728838800)
               #:home           'NO
               #:away           'TB
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671714
               #:name           "Cleveland Browns at Philadelphia Eagles"
               #:short-name     "CLE @ PHI"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728838800)
               #:home           'PHI
               #:away           'CLE
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671625
               #:name           "Washington Commanders at Baltimore Ravens"
               #:short-name     "WSH @ BAL"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728838800)
               #:home           'BAL
               #:away           'WSH
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671655
               #:name           "Los Angeles Chargers at Denver Broncos"
               #:short-name     "LAC @ DEN"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728849900)
               #:home           'DEN
               #:away           'LAC
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671657
               #:name           "Pittsburgh Steelers at Las Vegas Raiders"
               #:short-name     "PIT @ LV"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728849900)
               #:home           'LV
               #:away           'PIT
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671764
               #:name           "Detroit Lions at Dallas Cowboys"
               #:short-name     "DET @ DAL"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728851100)
               #:home           'DAL
               #:away           'DET
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671769
               #:name           "Atlanta Falcons at Carolina Panthers"
               #:short-name     "ATL @ CAR"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728851100)
               #:home           'CAR
               #:away           'ATL
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671791
               #:name           "Cincinnati Bengals at New York Giants"
               #:short-name     "CIN @ NYG"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728865200)
               #:home           'NYG
               #:away           'CIN
)
 2024 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671684
               #:name           "Buffalo Bills at New York Jets"
               #:short-name     "BUF @ NYJ"
               #:year           2024
               #:week           5
               #:time           (secs->gametime 1728951300)
               #:home           'NYJ
               #:away           'BUF
)
 2024 6)

