(define-module (bad-cat nfldb data sched year-2024 week-15)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671818
               #:name           "Los Angeles Rams at San Francisco 49ers"
               #:short-name     "LAR @ SF"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734056100)
               #:home           'SF
               #:away           'LAR
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671854
               #:name           "Kansas City Chiefs at Cleveland Browns"
               #:short-name     "KC @ CLE"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734289200)
               #:home           'CLE
               #:away           'KC
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671825
               #:name           "Cincinnati Bengals at Tennessee Titans"
               #:short-name     "CIN @ TEN"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734289200)
               #:home           'TEN
               #:away           'CIN
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671737
               #:name           "Washington Commanders at New Orleans Saints"
               #:short-name     "WSH @ NO"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734289200)
               #:home           'NO
               #:away           'WSH
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671639
               #:name           "Baltimore Ravens at New York Giants"
               #:short-name     "BAL @ NYG"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734289200)
               #:home           'NYG
               #:away           'BAL
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671731
               #:name           "Dallas Cowboys at Carolina Panthers"
               #:short-name     "DAL @ CAR"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734289200)
               #:home           'CAR
               #:away           'DAL
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671706
               #:name           "New York Jets at Jacksonville Jaguars"
               #:short-name     "NYJ @ JAX"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734289200)
               #:home           'JAX
               #:away           'NYJ
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671860
               #:name           "Miami Dolphins at Houston Texans"
               #:short-name     "MIA @ HOU"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734289200)
               #:home           'HOU
               #:away           'MIA
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671669
               #:name           "Indianapolis Colts at Denver Broncos"
               #:short-name     "IND @ DEN"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734301500)
               #:home           'DEN
               #:away           'IND
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671681
               #:name           "Buffalo Bills at Detroit Lions"
               #:short-name     "BUF @ DET"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734301500)
               #:home           'DET
               #:away           'BUF
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671766
               #:name           "Pittsburgh Steelers at Philadelphia Eagles"
               #:short-name     "PIT @ PHI"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734301500)
               #:home           'PHI
               #:away           'PIT
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671677
               #:name           "New England Patriots at Arizona Cardinals"
               #:short-name     "NE @ ARI"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734301500)
               #:home           'ARI
               #:away           'NE
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671762
               #:name           "Tampa Bay Buccaneers at Los Angeles Chargers"
               #:short-name     "TB @ LAC"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734301500)
               #:home           'LAC
               #:away           'TB
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671796
               #:name           "Green Bay Packers at Seattle Seahawks"
               #:short-name     "GB @ SEA"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734315600)
               #:home           'SEA
               #:away           'GB
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671489
               #:name           "Chicago Bears at Minnesota Vikings"
               #:short-name     "CHI @ MIN"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734400800)
               #:home           'MIN
               #:away           'CHI
)
 2024 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671697
               #:name           "Atlanta Falcons at Las Vegas Raiders"
               #:short-name     "ATL @ LV"
               #:year           2024
               #:week           14
               #:time           (secs->gametime 1734402600)
               #:home           'LV
               #:away           'ATL
)
 2024 15)

