(define-module (bad-cat nfldb data sched year-2024 week-18)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671834
               #:name           "Cleveland Browns at Baltimore Ravens"
               #:short-name     "CLE @ BAL"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736029800)
               #:home           'BAL
               #:away           'CLE
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671836
               #:name           "Cincinnati Bengals at Pittsburgh Steelers"
               #:short-name     "CIN @ PIT"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736042400)
               #:home           'PIT
               #:away           'CIN
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671827
               #:name           "Carolina Panthers at Atlanta Falcons"
               #:short-name     "CAR @ ATL"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'ATL
               #:away           'CAR
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671840
               #:name           "Washington Commanders at Dallas Cowboys"
               #:short-name     "WSH @ DAL"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'DAL
               #:away           'WSH
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671844
               #:name           "Chicago Bears at Green Bay Packers"
               #:short-name     "CHI @ GB"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'GB
               #:away           'CHI
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671826
               #:name           "Houston Texans at Tennessee Titans"
               #:short-name     "HOU @ TEN"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'TEN
               #:away           'HOU
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671837
               #:name           "Jacksonville Jaguars at Indianapolis Colts"
               #:short-name     "JAX @ IND"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'IND
               #:away           'JAX
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671831
               #:name           "Buffalo Bills at New England Patriots"
               #:short-name     "BUF @ NE"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'NE
               #:away           'BUF
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671841
               #:name           "New York Giants at Philadelphia Eagles"
               #:short-name     "NYG @ PHI"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'PHI
               #:away           'NYG
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671828
               #:name           "New Orleans Saints at Tampa Bay Buccaneers"
               #:short-name     "NO @ TB"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736103600)
               #:home           'TB
               #:away           'NO
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671838
               #:name           "Kansas City Chiefs at Denver Broncos"
               #:short-name     "KC @ DEN"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736115900)
               #:home           'DEN
               #:away           'KC
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671839
               #:name           "Los Angeles Chargers at Las Vegas Raiders"
               #:short-name     "LAC @ LV"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736115900)
               #:home           'LV
               #:away           'LAC
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671830
               #:name           "Seattle Seahawks at Los Angeles Rams"
               #:short-name     "SEA @ LAR"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736115900)
               #:home           'LAR
               #:away           'SEA
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671833
               #:name           "Miami Dolphins at New York Jets"
               #:short-name     "MIA @ NYJ"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736115900)
               #:home           'NYJ
               #:away           'MIA
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671845
               #:name           "San Francisco 49ers at Arizona Cardinals"
               #:short-name     "SF @ ARI"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736115900)
               #:home           'ARI
               #:away           'SF
)
 2024 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671843
               #:name           "Minnesota Vikings at Detroit Lions"
               #:short-name     "MIN @ DET"
               #:year           2024
               #:week           17
               #:time           (secs->gametime 1736130000)
               #:home           'DET
               #:away           'MIN
)
 2024 18)

