(define-module (bad-cat nfldb data sched year-2024 week-13)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671492
               #:name           "Chicago Bears at Detroit Lions"
               #:short-name     "CHI @ DET"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1732818600)
               #:home           'DET
               #:away           'CHI
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671779
               #:name           "New York Giants at Dallas Cowboys"
               #:short-name     "NYG @ DAL"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1732833000)
               #:home           'DAL
               #:away           'NYG
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671798
               #:name           "Miami Dolphins at Green Bay Packers"
               #:short-name     "MIA @ GB"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1732846800)
               #:home           'GB
               #:away           'MIA
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671806
               #:name           "Las Vegas Raiders at Kansas City Chiefs"
               #:short-name     "LV @ KC"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1732914000)
               #:home           'KC
               #:away           'LV
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671649
               #:name           "Los Angeles Chargers at Atlanta Falcons"
               #:short-name     "LAC @ ATL"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733079600)
               #:home           'ATL
               #:away           'LAC
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671627
               #:name           "Pittsburgh Steelers at Cincinnati Bengals"
               #:short-name     "PIT @ CIN"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733079600)
               #:home           'CIN
               #:away           'PIT
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671726
               #:name           "Arizona Cardinals at Minnesota Vikings"
               #:short-name     "ARI @ MIN"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733079600)
               #:home           'MIN
               #:away           'ARI
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671620
               #:name           "Indianapolis Colts at New England Patriots"
               #:short-name     "IND @ NE"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733079600)
               #:home           'NE
               #:away           'IND
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671703
               #:name           "Seattle Seahawks at New York Jets"
               #:short-name     "SEA @ NYJ"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733079600)
               #:home           'NYJ
               #:away           'SEA
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671743
               #:name           "Tennessee Titans at Washington Commanders"
               #:short-name     "TEN @ WSH"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733079600)
               #:home           'WSH
               #:away           'TEN
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671705
               #:name           "Houston Texans at Jacksonville Jaguars"
               #:short-name     "HOU @ JAX"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733079600)
               #:home           'JAX
               #:away           'HOU
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671753
               #:name           "Los Angeles Rams at New Orleans Saints"
               #:short-name     "LAR @ NO"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733090700)
               #:home           'NO
               #:away           'LAR
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671752
               #:name           "Tampa Bay Buccaneers at Carolina Panthers"
               #:short-name     "TB @ CAR"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733090700)
               #:home           'CAR
               #:away           'TB
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671666
               #:name           "Philadelphia Eagles at Baltimore Ravens"
               #:short-name     "PHI @ BAL"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733091900)
               #:home           'BAL
               #:away           'PHI
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671781
               #:name           "San Francisco 49ers at Buffalo Bills"
               #:short-name     "SF @ BUF"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733106000)
               #:home           'BUF
               #:away           'SF
)
 2024 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671686
               #:name           "Cleveland Browns at Denver Broncos"
               #:short-name     "CLE @ DEN"
               #:year           2024
               #:week           12
               #:time           (secs->gametime 1733192100)
               #:home           'DEN
               #:away           'CLE
)
 2024 13)

