(define-module (bad-cat nfldb data sched year-2024 week-16)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671749
               #:name           "Denver Broncos at Los Angeles Chargers"
               #:short-name     "DEN @ LAC"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734660900)
               #:home           'LAC
               #:away           'DEN
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671780
               #:name           "Houston Texans at Kansas City Chiefs"
               #:short-name     "HOU @ KC"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734807600)
               #:home           'KC
               #:away           'HOU
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671778
               #:name           "Pittsburgh Steelers at Baltimore Ravens"
               #:short-name     "PIT @ BAL"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734820200)
               #:home           'BAL
               #:away           'PIT
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671729
               #:name           "New York Giants at Atlanta Falcons"
               #:short-name     "NYG @ ATL"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734894000)
               #:home           'ATL
               #:away           'NYG
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671868
               #:name           "Detroit Lions at Chicago Bears"
               #:short-name     "DET @ CHI"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734894000)
               #:home           'CHI
               #:away           'DET
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671811
               #:name           "Cleveland Browns at Cincinnati Bengals"
               #:short-name     "CLE @ CIN"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734894000)
               #:home           'CIN
               #:away           'CLE
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671862
               #:name           "Tennessee Titans at Indianapolis Colts"
               #:short-name     "TEN @ IND"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734894000)
               #:home           'IND
               #:away           'TEN
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671621
               #:name           "Los Angeles Rams at New York Jets"
               #:short-name     "LAR @ NYJ"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734894000)
               #:home           'NYJ
               #:away           'LAR
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671717
               #:name           "Philadelphia Eagles at Washington Commanders"
               #:short-name     "PHI @ WSH"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734894000)
               #:home           'WSH
               #:away           'PHI
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671732
               #:name           "Arizona Cardinals at Carolina Panthers"
               #:short-name     "ARI @ CAR"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734894000)
               #:home           'CAR
               #:away           'ARI
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671759
               #:name           "Minnesota Vikings at Seattle Seahawks"
               #:short-name     "MIN @ SEA"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734905100)
               #:home           'SEA
               #:away           'MIN
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671494
               #:name           "New England Patriots at Buffalo Bills"
               #:short-name     "NE @ BUF"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734906300)
               #:home           'BUF
               #:away           'NE
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671673
               #:name           "Jacksonville Jaguars at Las Vegas Raiders"
               #:short-name     "JAX @ LV"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734906300)
               #:home           'LV
               #:away           'JAX
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671874
               #:name           "San Francisco 49ers at Miami Dolphins"
               #:short-name     "SF @ MIA"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734906300)
               #:home           'MIA
               #:away           'SF
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671790
               #:name           "Tampa Bay Buccaneers at Dallas Cowboys"
               #:short-name     "TB @ DAL"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1734920400)
               #:home           'DAL
               #:away           'TB
)
 2024 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671692
               #:name           "New Orleans Saints at Green Bay Packers"
               #:short-name     "NO @ GB"
               #:year           2024
               #:week           15
               #:time           (secs->gametime 1735006500)
               #:home           'GB
               #:away           'NO
)
 2024 16)

