(define-module (bad-cat nfldb data sched year-2024 week-11)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671813
               #:name           "Washington Commanders at Philadelphia Eagles"
               #:short-name     "WSH @ PHI"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731636900)
               #:home           'PHI
               #:away           'WSH
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671869
               #:name           "Green Bay Packers at Chicago Bears"
               #:short-name     "GB @ CHI"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'CHI
               #:away           'GB
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671642
               #:name           "Jacksonville Jaguars at Detroit Lions"
               #:short-name     "JAX @ DET"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'DET
               #:away           'JAX
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671824
               #:name           "Minnesota Vikings at Tennessee Titans"
               #:short-name     "MIN @ TEN"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'TEN
               #:away           'MIN
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671851
               #:name           "Las Vegas Raiders at Miami Dolphins"
               #:short-name     "LV @ MIA"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'MIA
               #:away           'LV
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671701
               #:name           "Los Angeles Rams at New England Patriots"
               #:short-name     "LAR @ NE"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'NE
               #:away           'LAR
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671746
               #:name           "Cleveland Browns at New Orleans Saints"
               #:short-name     "CLE @ NO"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'NO
               #:away           'CLE
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671782
               #:name           "Indianapolis Colts at New York Jets"
               #:short-name     "IND @ NYJ"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'NYJ
               #:away           'IND
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671630
               #:name           "Baltimore Ravens at Pittsburgh Steelers"
               #:short-name     "BAL @ PIT"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731870000)
               #:home           'PIT
               #:away           'BAL
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671748
               #:name           "Atlanta Falcons at Denver Broncos"
               #:short-name     "ATL @ DEN"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731881100)
               #:home           'DEN
               #:away           'ATL
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671757
               #:name           "Seattle Seahawks at San Francisco 49ers"
               #:short-name     "SEA @ SF"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731881100)
               #:home           'SF
               #:away           'SEA
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671665
               #:name           "Kansas City Chiefs at Buffalo Bills"
               #:short-name     "KC @ BUF"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731882300)
               #:home           'BUF
               #:away           'KC
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671675
               #:name           "Cincinnati Bengals at Los Angeles Chargers"
               #:short-name     "CIN @ LAC"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731896400)
               #:home           'LAC
               #:away           'CIN
)
 2024 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401671694
               #:name           "Houston Texans at Dallas Cowboys"
               #:short-name     "HOU @ DAL"
               #:year           2024
               #:week           10
               #:time           (secs->gametime 1731982500)
               #:home           'DAL
               #:away           'HOU
)
 2024 11)

