(define-module (bad-cat nfldb data sched year-2025 week-06)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772940
               #:name           "Philadelphia Eagles at New York Giants"
               #:short-name     "PHI @ NYG"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760055300)
               #:home           'NYG
               #:away           'PHI
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772634
               #:name           "Denver Broncos at New York Jets"
               #:short-name     "DEN VS NYJ"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760275800)
               #:home           'NYJ
               #:away           'DEN
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772856
               #:name           "Arizona Cardinals at Indianapolis Colts"
               #:short-name     "ARI @ IND"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'IND
               #:away           'ARI
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772750
               #:name           "Los Angeles Chargers at Miami Dolphins"
               #:short-name     "LAC @ MIA"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'MIA
               #:away           'LAC
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772748
               #:name           "Cleveland Browns at Pittsburgh Steelers"
               #:short-name     "CLE @ PIT"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'PIT
               #:away           'CLE
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772749
               #:name           "San Francisco 49ers at Tampa Bay Buccaneers"
               #:short-name     "SF @ TB"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'TB
               #:away           'SF
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772858
               #:name           "Dallas Cowboys at Carolina Panthers"
               #:short-name     "DAL @ CAR"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'CAR
               #:away           'DAL
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772857
               #:name           "Seattle Seahawks at Jacksonville Jaguars"
               #:short-name     "SEA @ JAX"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'JAX
               #:away           'SEA
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772855
               #:name           "Los Angeles Rams at Baltimore Ravens"
               #:short-name     "LAR @ BAL"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'BAL
               #:away           'LAR
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772859
               #:name           "Tennessee Titans at Las Vegas Raiders"
               #:short-name     "TEN @ LV"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760299500)
               #:home           'LV
               #:away           'TEN
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772752
               #:name           "Cincinnati Bengals at Green Bay Packers"
               #:short-name     "CIN @ GB"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760300700)
               #:home           'GB
               #:away           'CIN
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772751
               #:name           "New England Patriots at New Orleans Saints"
               #:short-name     "NE @ NO"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760300700)
               #:home           'NO
               #:away           'NE
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772923
               #:name           "Detroit Lions at Kansas City Chiefs"
               #:short-name     "DET @ KC"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760314800)
               #:home           'KC
               #:away           'DET
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772815
               #:name           "Buffalo Bills at Atlanta Falcons"
               #:short-name     "BUF @ ATL"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760397300)
               #:home           'ATL
               #:away           'BUF
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772717
               #:name           "Chicago Bears at Washington Commanders"
               #:short-name     "CHI @ WSH"
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760400900)
               #:home           'WSH
               #:away           'CHI
)
 2025 6)

