(define-module (bad-cat nfldb data sched year-2025 week-18)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772966
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'ATL
               #:away           'NO
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772967
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'BUF
               #:away           'NYJ
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772965
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'CHI
               #:away           'DET
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772964
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'CIN
               #:away           'CLE
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772956
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'DEN
               #:away           'LAC
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772957
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'LV
               #:away           'KC
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772955
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'LAR
               #:away           'ARI
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772968
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'MIN
               #:away           'GB
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772958
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'NE
               #:away           'MIA
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772963
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'NYG
               #:away           'DAL
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772959
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'PHI
               #:away           'WSH
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772960
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'PIT
               #:away           'BAL
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772961
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'SF
               #:away           'SEA
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772969
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'TB
               #:away           'CAR
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772970
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'JAX
               #:away           'TEN
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772962
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'HOU
               #:away           'IND
)
 2025 18)

