(define-module (bad-cat nfldb data sched year-2025 week-12)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772946
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763691300)
               #:home           'HOU
               #:away           'BUF
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772780
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'CHI
               #:away           'PIT
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772781
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'CIN
               #:away           'NE
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772888
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'DET
               #:away           'NYG
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772887
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'GB
               #:away           'MIN
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772886
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'TEN
               #:away           'SEA
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772779
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'KC
               #:away           'IND
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772782
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'BAL
               #:away           'NYJ
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772784
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763935500)
               #:home           'LV
               #:away           'CLE
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772783
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763935500)
               #:home           'ARI
               #:away           'JAX
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772890
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763936700)
               #:home           'DAL
               #:away           'PHI
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772889
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763936700)
               #:home           'NO
               #:away           'ATL
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772929
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763950800)
               #:home           'LAR
               #:away           'TB
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772820
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1764036900)
               #:home           'SF
               #:away           'CAR
)
 2025 12)

