(define-module (bad-cat nfldb data sched year-2025 week-13)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772891
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764270000)
               #:home           'DET
               #:away           'GB
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772694
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764282600)
               #:home           'DAL
               #:away           'KC
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772930
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764296400)
               #:home           'BAL
               #:away           'CIN
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772621
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764363600)
               #:home           'PHI
               #:away           'CHI
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772785
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764529200)
               #:home           'CLE
               #:away           'SF
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772786
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764529200)
               #:home           'TEN
               #:away           'JAX
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772787
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764529200)
               #:home           'IND
               #:away           'HOU
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772892
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764529200)
               #:home           'MIA
               #:away           'NO
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772893
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764529200)
               #:home           'NYJ
               #:away           'ATL
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772895
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764529200)
               #:home           'TB
               #:away           'ARI
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772894
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764529200)
               #:home           'CAR
               #:away           'LAR
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772896
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764540300)
               #:home           'SEA
               #:away           'MIN
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772789
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764541500)
               #:home           'PIT
               #:away           'BUF
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772788
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764541500)
               #:home           'LAC
               #:away           'LV
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772931
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764555600)
               #:home           'WSH
               #:away           'DEN
)
 2025 13)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772821
               #:year           2025
               #:week           12
               #:time           (secs->gametime 1764641700)
               #:home           'NE
               #:away           'NYG
)
 2025 13)

