(define-module (bad-cat nfldb data sched year-2025 week-02)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772936
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757636100)
               #:home           'GB
               #:away           'WSH
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772725
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'CIN
               #:away           'JAX
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772834
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'DAL
               #:away           'NYG
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772835
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'DET
               #:away           'CHI
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772724
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'TEN
               #:away           'LAR
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772728
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'MIA
               #:away           'NE
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772833
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'NO
               #:away           'SF
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772727
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'NYJ
               #:away           'BUF
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772836
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'PIT
               #:away           'SEA
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772726
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'BAL
               #:away           'CLE
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772729
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757880300)
               #:home           'IND
               #:away           'DEN
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772730
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757880300)
               #:home           'ARI
               #:away           'CAR
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772837
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757881500)
               #:home           'KC
               #:away           'PHI
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772919
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757895600)
               #:home           'MIN
               #:away           'ATL
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772715
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757977200)
               #:home           'HOU
               #:away           'TB
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772811
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757988000)
               #:home           'LV
               #:away           'LAC
)
 2025 2)

