(define-module (bad-cat nfldb data sched year-2025 week-18)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772966
               #:name           "New Orleans Saints at Atlanta Falcons"
               #:short-name     "NO @ ATL"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'ATL
               #:away           'NO
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772967
               #:name           "New York Jets at Buffalo Bills"
               #:short-name     "NYJ @ BUF"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'BUF
               #:away           'NYJ
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772965
               #:name           "Detroit Lions at Chicago Bears"
               #:short-name     "DET @ CHI"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'CHI
               #:away           'DET
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772964
               #:name           "Cleveland Browns at Cincinnati Bengals"
               #:short-name     "CLE @ CIN"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'CIN
               #:away           'CLE
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772956
               #:name           "Los Angeles Chargers at Denver Broncos"
               #:short-name     "LAC @ DEN"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'DEN
               #:away           'LAC
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772957
               #:name           "Kansas City Chiefs at Las Vegas Raiders"
               #:short-name     "KC @ LV"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'LV
               #:away           'KC
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772955
               #:name           "Arizona Cardinals at Los Angeles Rams"
               #:short-name     "ARI @ LAR"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'LAR
               #:away           'ARI
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772968
               #:name           "Green Bay Packers at Minnesota Vikings"
               #:short-name     "GB @ MIN"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'MIN
               #:away           'GB
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772958
               #:name           "Miami Dolphins at New England Patriots"
               #:short-name     "MIA @ NE"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'NE
               #:away           'MIA
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772963
               #:name           "Dallas Cowboys at New York Giants"
               #:short-name     "DAL @ NYG"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'NYG
               #:away           'DAL
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772959
               #:name           "Washington Commanders at Philadelphia Eagles"
               #:short-name     "WSH @ PHI"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'PHI
               #:away           'WSH
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772960
               #:name           "Baltimore Ravens at Pittsburgh Steelers"
               #:short-name     "BAL @ PIT"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'PIT
               #:away           'BAL
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772961
               #:name           "Seattle Seahawks at San Francisco 49ers"
               #:short-name     "SEA @ SF"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'SF
               #:away           'SEA
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772969
               #:name           "Carolina Panthers at Tampa Bay Buccaneers"
               #:short-name     "CAR @ TB"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'TB
               #:away           'CAR
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772970
               #:name           "Tennessee Titans at Jacksonville Jaguars"
               #:short-name     "TEN @ JAX"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'JAX
               #:away           'TEN
)
 2025 18)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772962
               #:name           "Indianapolis Colts at Houston Texans"
               #:short-name     "IND @ HOU"
               #:year           2025
               #:week           17
               #:time           (secs->gametime 1767506400)
               #:home           'HOU
               #:away           'IND
)
 2025 18)

