(define-module (bad-cat nfldb data sched year-2025 week-16)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772949
               #:name           "Los Angeles Rams at Seattle Seahawks"
               #:short-name     "LAR @ SEA"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766110500)
               #:home           'SEA
               #:away           'LAR
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772613
               #:name           "Green Bay Packers at Chicago Bears"
               #:short-name     "GB @ CHI"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766210400)
               #:home           'CHI
               #:away           'GB
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772612
               #:name           "Philadelphia Eagles at Washington Commanders"
               #:short-name     "PHI @ WSH"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766210400)
               #:home           'WSH
               #:away           'PHI
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772802
               #:name           "Buffalo Bills at Cleveland Browns"
               #:short-name     "BUF @ CLE"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'CLE
               #:away           'BUF
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772910
               #:name           "Los Angeles Chargers at Dallas Cowboys"
               #:short-name     "LAC @ DAL"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'DAL
               #:away           'LAC
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772803
               #:name           "Kansas City Chiefs at Tennessee Titans"
               #:short-name     "KC @ TEN"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'TEN
               #:away           'KC
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772801
               #:name           "New York Jets at New Orleans Saints"
               #:short-name     "NYJ @ NO"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'NO
               #:away           'NYJ
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772911
               #:name           "Minnesota Vikings at New York Giants"
               #:short-name     "MIN @ NYG"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'NYG
               #:away           'MIN
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772912
               #:name           "Tampa Bay Buccaneers at Carolina Panthers"
               #:short-name     "TB @ CAR"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'CAR
               #:away           'TB
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772804
               #:name           "New England Patriots at Baltimore Ravens"
               #:short-name     "NE @ BAL"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'BAL
               #:away           'NE
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772913
               #:name           "Jacksonville Jaguars at Denver Broncos"
               #:short-name     "JAX @ DEN"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766354700)
               #:home           'DEN
               #:away           'JAX
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772914
               #:name           "Atlanta Falcons at Arizona Cardinals"
               #:short-name     "ATL @ ARI"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766354700)
               #:home           'ARI
               #:away           'ATL
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772806
               #:name           "Pittsburgh Steelers at Detroit Lions"
               #:short-name     "PIT @ DET"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766355900)
               #:home           'DET
               #:away           'PIT
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772805
               #:name           "Las Vegas Raiders at Houston Texans"
               #:short-name     "LV @ HOU"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766355900)
               #:home           'HOU
               #:away           'LV
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772934
               #:name           "Cincinnati Bengals at Miami Dolphins"
               #:short-name     "CIN @ MIA"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766370000)
               #:home           'MIA
               #:away           'CIN
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772824
               #:name           "San Francisco 49ers at Indianapolis Colts"
               #:short-name     "SF @ IND"
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766456100)
               #:home           'IND
               #:away           'SF
)
 2025 16)

