(define-module (bad-cat nfldb data sched year-2025 week-05)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772939
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759450500)
               #:home           'LAR
               #:away           'SF
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772633
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759671000)
               #:home           'CLE
               #:away           'MIN
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772851
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759683600)
               #:home           'IND
               #:away           'LV
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772744
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759683600)
               #:home           'NO
               #:away           'NYG
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772850
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759683600)
               #:home           'NYJ
               #:away           'DAL
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772745
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759683600)
               #:home           'PHI
               #:away           'DEN
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772852
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759683600)
               #:home           'CAR
               #:away           'MIA
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772743
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759683600)
               #:home           'BAL
               #:away           'HOU
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772747
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759694700)
               #:home           'ARI
               #:away           'TEN
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772746
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759694700)
               #:home           'SEA
               #:away           'TB
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772854
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759695900)
               #:home           'CIN
               #:away           'DET
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772853
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759695900)
               #:home           'LAC
               #:away           'WSH
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772922
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759710000)
               #:home           'BUF
               #:away           'NE
)
 2025 5)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772814
               #:year           2025
               #:week           4
               #:time           (secs->gametime 1759796100)
               #:home           'JAX
               #:away           'KC
)
 2025 5)

