(define-module (bad-cat nfldb data sched year-2025 week-16)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772949
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766110500)
               #:home           'SEA
               #:away           'LAR
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772613
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766210400)
               #:home           'CHI
               #:away           'GB
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772612
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766210400)
               #:home           'WSH
               #:away           'PHI
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772802
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'CLE
               #:away           'BUF
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772910
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'DAL
               #:away           'LAC
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772803
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'TEN
               #:away           'KC
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772801
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'NO
               #:away           'NYJ
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772911
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'NYG
               #:away           'MIN
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772912
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'CAR
               #:away           'TB
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772804
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766343600)
               #:home           'BAL
               #:away           'NE
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772913
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766354700)
               #:home           'DEN
               #:away           'JAX
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772914
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766354700)
               #:home           'ARI
               #:away           'ATL
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772806
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766355900)
               #:home           'DET
               #:away           'PIT
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772805
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766355900)
               #:home           'HOU
               #:away           'LV
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772934
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766370000)
               #:home           'MIA
               #:away           'CIN
)
 2025 16)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772824
               #:year           2025
               #:week           15
               #:time           (secs->gametime 1766456100)
               #:home           'IND
               #:away           'SF
)
 2025 16)

