(define-module (bad-cat nfldb data sched year-2025 week-02)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772936
               #:name           "Washington Commanders at Green Bay Packers"
               #:short-name     "WSH @ GB"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757636100)
               #:home           'GB
               #:away           'WSH
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772725
               #:name           "Jacksonville Jaguars at Cincinnati Bengals"
               #:short-name     "JAX @ CIN"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'CIN
               #:away           'JAX
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772834
               #:name           "New York Giants at Dallas Cowboys"
               #:short-name     "NYG @ DAL"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'DAL
               #:away           'NYG
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772835
               #:name           "Chicago Bears at Detroit Lions"
               #:short-name     "CHI @ DET"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'DET
               #:away           'CHI
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772724
               #:name           "Los Angeles Rams at Tennessee Titans"
               #:short-name     "LAR @ TEN"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'TEN
               #:away           'LAR
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772728
               #:name           "New England Patriots at Miami Dolphins"
               #:short-name     "NE @ MIA"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'MIA
               #:away           'NE
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772833
               #:name           "San Francisco 49ers at New Orleans Saints"
               #:short-name     "SF @ NO"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'NO
               #:away           'SF
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772727
               #:name           "Buffalo Bills at New York Jets"
               #:short-name     "BUF @ NYJ"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'NYJ
               #:away           'BUF
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772836
               #:name           "Seattle Seahawks at Pittsburgh Steelers"
               #:short-name     "SEA @ PIT"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'PIT
               #:away           'SEA
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772726
               #:name           "Cleveland Browns at Baltimore Ravens"
               #:short-name     "CLE @ BAL"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757869200)
               #:home           'BAL
               #:away           'CLE
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772729
               #:name           "Denver Broncos at Indianapolis Colts"
               #:short-name     "DEN @ IND"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757880300)
               #:home           'IND
               #:away           'DEN
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772730
               #:name           "Carolina Panthers at Arizona Cardinals"
               #:short-name     "CAR @ ARI"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757880300)
               #:home           'ARI
               #:away           'CAR
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772837
               #:name           "Philadelphia Eagles at Kansas City Chiefs"
               #:short-name     "PHI @ KC"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757881500)
               #:home           'KC
               #:away           'PHI
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772919
               #:name           "Atlanta Falcons at Minnesota Vikings"
               #:short-name     "ATL @ MIN"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757895600)
               #:home           'MIN
               #:away           'ATL
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772715
               #:name           "Tampa Bay Buccaneers at Houston Texans"
               #:short-name     "TB @ HOU"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757977200)
               #:home           'HOU
               #:away           'TB
)
 2025 2)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772811
               #:name           "Los Angeles Chargers at Las Vegas Raiders"
               #:short-name     "LAC @ LV"
               #:year           2025
               #:week           1
               #:time           (secs->gametime 1757988000)
               #:home           'LV
               #:away           'LAC
)
 2025 2)

