(define-module (bad-cat nfldb data sched year-2025 week-15)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772948
               #:name           "Atlanta Falcons at Tampa Bay Buccaneers"
               #:short-name     "ATL @ TB"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765505700)
               #:home           'TB
               #:away           'ATL
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772904
               #:name           "Cleveland Browns at Chicago Bears"
               #:short-name     "CLE @ CHI"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'CHI
               #:away           'CLE
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772796
               #:name           "Baltimore Ravens at Cincinnati Bengals"
               #:short-name     "BAL @ CIN"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'CIN
               #:away           'BAL
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772798
               #:name           "Los Angeles Chargers at Kansas City Chiefs"
               #:short-name     "LAC @ KC"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'KC
               #:away           'LAC
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772795
               #:name           "Buffalo Bills at New England Patriots"
               #:short-name     "BUF @ NE"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'NE
               #:away           'BUF
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772905
               #:name           "Washington Commanders at New York Giants"
               #:short-name     "WSH @ NYG"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'NYG
               #:away           'WSH
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772906
               #:name           "Las Vegas Raiders at Philadelphia Eagles"
               #:short-name     "LV @ PHI"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'PHI
               #:away           'LV
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772797
               #:name           "New York Jets at Jacksonville Jaguars"
               #:short-name     "NYJ @ JAX"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'JAX
               #:away           'NYJ
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772903
               #:name           "Arizona Cardinals at Houston Texans"
               #:short-name     "ARI @ HOU"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'HOU
               #:away           'ARI
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772800
               #:name           "Green Bay Packers at Denver Broncos"
               #:short-name     "GB @ DEN"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'DEN
               #:away           'GB
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772909
               #:name           "Detroit Lions at Los Angeles Rams"
               #:short-name     "DET @ LAR"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'LAR
               #:away           'DET
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772908
               #:name           "Carolina Panthers at New Orleans Saints"
               #:short-name     "CAR @ NO"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'NO
               #:away           'CAR
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772907
               #:name           "Tennessee Titans at San Francisco 49ers"
               #:short-name     "TEN @ SF"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'SF
               #:away           'TEN
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772799
               #:name           "Indianapolis Colts at Seattle Seahawks"
               #:short-name     "IND @ SEA"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'SEA
               #:away           'IND
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772933
               #:name           "Minnesota Vikings at Dallas Cowboys"
               #:short-name     "MIN @ DAL"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765765200)
               #:home           'DAL
               #:away           'MIN
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772823
               #:name           "Miami Dolphins at Pittsburgh Steelers"
               #:short-name     "MIA @ PIT"
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765851300)
               #:home           'PIT
               #:away           'MIA
)
 2025 15)

