(define-module (bad-cat nfldb data sched year-2025 week-09)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772943
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1761869700)
               #:home           'MIA
               #:away           'BAL
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772765
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'CIN
               #:away           'CHI
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772871
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'DET
               #:away           'MIN
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772872
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'GB
               #:away           'CAR
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772764
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'TEN
               #:away           'LAC
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772763
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'NE
               #:away           'ATL
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772767
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'NYG
               #:away           'SF
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772766
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'PIT
               #:away           'IND
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772870
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'HOU
               #:away           'DEN
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772873
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762121100)
               #:home           'LV
               #:away           'JAX
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772874
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762121100)
               #:home           'LAR
               #:away           'NO
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772768
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762122300)
               #:home           'BUF
               #:away           'KC
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772926
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762136400)
               #:home           'WSH
               #:away           'SEA
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772818
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762222500)
               #:home           'DAL
               #:away           'ARI
)
 2025 9)

