(define-module (bad-cat nfldb data sched year-2025 week-06)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772940
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760055300)
               #:home           'NYG
               #:away           'PHI
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772634
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760275800)
               #:home           'NYJ
               #:away           'DEN
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772856
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'IND
               #:away           'ARI
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772750
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'MIA
               #:away           'LAC
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772748
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'PIT
               #:away           'CLE
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772749
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'TB
               #:away           'SF
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772858
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'CAR
               #:away           'DAL
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772857
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'JAX
               #:away           'SEA
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772855
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760288400)
               #:home           'BAL
               #:away           'LAR
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772859
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760299500)
               #:home           'LV
               #:away           'TEN
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772752
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760300700)
               #:home           'GB
               #:away           'CIN
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772751
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760300700)
               #:home           'NO
               #:away           'NE
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772923
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760314800)
               #:home           'KC
               #:away           'DET
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772815
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760397300)
               #:home           'ATL
               #:away           'BUF
)
 2025 6)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772717
               #:year           2025
               #:week           5
               #:time           (secs->gametime 1760400900)
               #:home           'WSH
               #:away           'CHI
)
 2025 6)

