(define-module (bad-cat nfldb data sched year-2025 week-12)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772946
               #:name           "Buffalo Bills at Houston Texans"
               #:short-name     "BUF @ HOU"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763691300)
               #:home           'HOU
               #:away           'BUF
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772780
               #:name           "Pittsburgh Steelers at Chicago Bears"
               #:short-name     "PIT @ CHI"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'CHI
               #:away           'PIT
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772781
               #:name           "New England Patriots at Cincinnati Bengals"
               #:short-name     "NE @ CIN"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'CIN
               #:away           'NE
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772888
               #:name           "New York Giants at Detroit Lions"
               #:short-name     "NYG @ DET"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'DET
               #:away           'NYG
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772887
               #:name           "Minnesota Vikings at Green Bay Packers"
               #:short-name     "MIN @ GB"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'GB
               #:away           'MIN
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772886
               #:name           "Seattle Seahawks at Tennessee Titans"
               #:short-name     "SEA @ TEN"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'TEN
               #:away           'SEA
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772779
               #:name           "Indianapolis Colts at Kansas City Chiefs"
               #:short-name     "IND @ KC"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'KC
               #:away           'IND
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772782
               #:name           "New York Jets at Baltimore Ravens"
               #:short-name     "NYJ @ BAL"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763924400)
               #:home           'BAL
               #:away           'NYJ
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772784
               #:name           "Cleveland Browns at Las Vegas Raiders"
               #:short-name     "CLE @ LV"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763935500)
               #:home           'LV
               #:away           'CLE
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772783
               #:name           "Jacksonville Jaguars at Arizona Cardinals"
               #:short-name     "JAX @ ARI"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763935500)
               #:home           'ARI
               #:away           'JAX
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772890
               #:name           "Philadelphia Eagles at Dallas Cowboys"
               #:short-name     "PHI @ DAL"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763936700)
               #:home           'DAL
               #:away           'PHI
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772889
               #:name           "Atlanta Falcons at New Orleans Saints"
               #:short-name     "ATL @ NO"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763936700)
               #:home           'NO
               #:away           'ATL
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772929
               #:name           "Tampa Bay Buccaneers at Los Angeles Rams"
               #:short-name     "TB @ LAR"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1763950800)
               #:home           'LAR
               #:away           'TB
)
 2025 12)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772820
               #:name           "Carolina Panthers at San Francisco 49ers"
               #:short-name     "CAR @ SF"
               #:year           2025
               #:week           11
               #:time           (secs->gametime 1764036900)
               #:home           'SF
               #:away           'CAR
)
 2025 12)

