(define-module (bad-cat nfldb data sched year-2025 week-08)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 13

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772942
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761264900)
               #:home           'LAC
               #:away           'MIN
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772760
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'ATL
               #:away           'MIA
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772758
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'CIN
               #:away           'NYJ
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772868
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'NE
               #:away           'CLE
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772867
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'PHI
               #:away           'NYG
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772865
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'CAR
               #:away           'BUF
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772759
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'BAL
               #:away           'CHI
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772866
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'HOU
               #:away           'SF
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772869
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761509100)
               #:home           'NO
               #:away           'TB
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772762
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761510300)
               #:home           'DEN
               #:away           'DAL
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772761
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761510300)
               #:home           'IND
               #:away           'TEN
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772925
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761524400)
               #:home           'PIT
               #:away           'GB
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772817
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761610500)
               #:home           'KC
               #:away           'WSH
)
 2025 8)

