(define-module (bad-cat nfldb data sched year-2025 week-03)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772937
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758240900)
               #:home           'BUF
               #:away           'MIA
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772842
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'CLE
               #:away           'GB
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772733
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'TEN
               #:away           'IND
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772731
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'MIN
               #:away           'CIN
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772732
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'NE
               #:away           'PIT
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772839
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'PHI
               #:away           'LAR
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772840
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'TB
               #:away           'NYJ
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772841
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'WSH
               #:away           'LV
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772838
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'CAR
               #:away           'ATL
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772734
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'JAX
               #:away           'HOU
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772735
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758485100)
               #:home           'LAC
               #:away           'DEN
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772736
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758485100)
               #:home           'SEA
               #:away           'NO
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772844
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758486300)
               #:home           'CHI
               #:away           'DAL
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772843
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758486300)
               #:home           'SF
               #:away           'ARI
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772920
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758500400)
               #:home           'NYG
               #:away           'KC
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772812
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758586500)
               #:home           'BAL
               #:away           'DET
)
 2025 3)

