(define-module (bad-cat nfldb data sched year-2025 week-01)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772510
               #:name           "Dallas Cowboys at Philadelphia Eagles"
               #:short-name     "DAL @ PHI"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757031600)
               #:home           'PHI
               #:away           'DAL
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772714
               #:name           "Kansas City Chiefs at Los Angeles Chargers"
               #:short-name     "KC VS LAC"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757116800)
               #:home           'LAC
               #:away           'KC
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772830
               #:name           "Tampa Bay Buccaneers at Atlanta Falcons"
               #:short-name     "TB @ ATL"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'ATL
               #:away           'TB
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772829
               #:name           "Cincinnati Bengals at Cleveland Browns"
               #:short-name     "CIN @ CLE"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'CLE
               #:away           'CIN
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772719
               #:name           "Miami Dolphins at Indianapolis Colts"
               #:short-name     "MIA @ IND"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'IND
               #:away           'MIA
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772720
               #:name           "Las Vegas Raiders at New England Patriots"
               #:short-name     "LV @ NE"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'NE
               #:away           'LV
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772718
               #:name           "Arizona Cardinals at New Orleans Saints"
               #:short-name     "ARI @ NO"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'NO
               #:away           'ARI
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772721
               #:name           "Pittsburgh Steelers at New York Jets"
               #:short-name     "PIT @ NYJ"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'NYJ
               #:away           'PIT
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772827
               #:name           "New York Giants at Washington Commanders"
               #:short-name     "NYG @ WSH"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'WSH
               #:away           'NYG
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772828
               #:name           "Carolina Panthers at Jacksonville Jaguars"
               #:short-name     "CAR @ JAX"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'JAX
               #:away           'CAR
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772832
               #:name           "Tennessee Titans at Denver Broncos"
               #:short-name     "TEN @ DEN"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757275500)
               #:home           'DEN
               #:away           'TEN
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772831
               #:name           "San Francisco 49ers at Seattle Seahawks"
               #:short-name     "SF @ SEA"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757275500)
               #:home           'SEA
               #:away           'SF
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772722
               #:name           "Detroit Lions at Green Bay Packers"
               #:short-name     "DET @ GB"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757276700)
               #:home           'GB
               #:away           'DET
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772723
               #:name           "Houston Texans at Los Angeles Rams"
               #:short-name     "HOU @ LAR"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757276700)
               #:home           'LAR
               #:away           'HOU
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772918
               #:name           "Baltimore Ravens at Buffalo Bills"
               #:short-name     "BAL @ BUF"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757290800)
               #:home           'BUF
               #:away           'BAL
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772810
               #:name           "Minnesota Vikings at Chicago Bears"
               #:short-name     "MIN @ CHI"
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757376900)
               #:home           'CHI
               #:away           'MIN
)
 2025 1)

