(define-module (bad-cat nfldb data sched year-2025 week-08)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 13

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772942
               #:name           "Minnesota Vikings at Los Angeles Chargers"
               #:short-name     "MIN @ LAC"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761264900)
               #:home           'LAC
               #:away           'MIN
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772760
               #:name           "Miami Dolphins at Atlanta Falcons"
               #:short-name     "MIA @ ATL"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'ATL
               #:away           'MIA
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772758
               #:name           "New York Jets at Cincinnati Bengals"
               #:short-name     "NYJ @ CIN"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'CIN
               #:away           'NYJ
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772868
               #:name           "Cleveland Browns at New England Patriots"
               #:short-name     "CLE @ NE"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'NE
               #:away           'CLE
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772867
               #:name           "New York Giants at Philadelphia Eagles"
               #:short-name     "NYG @ PHI"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'PHI
               #:away           'NYG
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772865
               #:name           "Buffalo Bills at Carolina Panthers"
               #:short-name     "BUF @ CAR"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'CAR
               #:away           'BUF
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772759
               #:name           "Chicago Bears at Baltimore Ravens"
               #:short-name     "CHI @ BAL"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'BAL
               #:away           'CHI
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772866
               #:name           "San Francisco 49ers at Houston Texans"
               #:short-name     "SF @ HOU"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761498000)
               #:home           'HOU
               #:away           'SF
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772869
               #:name           "Tampa Bay Buccaneers at New Orleans Saints"
               #:short-name     "TB @ NO"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761509100)
               #:home           'NO
               #:away           'TB
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772762
               #:name           "Dallas Cowboys at Denver Broncos"
               #:short-name     "DAL @ DEN"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761510300)
               #:home           'DEN
               #:away           'DAL
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772761
               #:name           "Tennessee Titans at Indianapolis Colts"
               #:short-name     "TEN @ IND"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761510300)
               #:home           'IND
               #:away           'TEN
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772925
               #:name           "Green Bay Packers at Pittsburgh Steelers"
               #:short-name     "GB @ PIT"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761524400)
               #:home           'PIT
               #:away           'GB
)
 2025 8)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772817
               #:name           "Washington Commanders at Kansas City Chiefs"
               #:short-name     "WSH @ KC"
               #:year           2025
               #:week           7
               #:time           (secs->gametime 1761610500)
               #:home           'KC
               #:away           'WSH
)
 2025 8)

