(define-module (bad-cat nfldb data sched year-2025 week-03)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772937
               #:name           "Miami Dolphins at Buffalo Bills"
               #:short-name     "MIA @ BUF"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758240900)
               #:home           'BUF
               #:away           'MIA
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772842
               #:name           "Green Bay Packers at Cleveland Browns"
               #:short-name     "GB @ CLE"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'CLE
               #:away           'GB
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772733
               #:name           "Indianapolis Colts at Tennessee Titans"
               #:short-name     "IND @ TEN"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'TEN
               #:away           'IND
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772731
               #:name           "Cincinnati Bengals at Minnesota Vikings"
               #:short-name     "CIN @ MIN"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'MIN
               #:away           'CIN
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772732
               #:name           "Pittsburgh Steelers at New England Patriots"
               #:short-name     "PIT @ NE"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'NE
               #:away           'PIT
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772839
               #:name           "Los Angeles Rams at Philadelphia Eagles"
               #:short-name     "LAR @ PHI"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'PHI
               #:away           'LAR
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772840
               #:name           "New York Jets at Tampa Bay Buccaneers"
               #:short-name     "NYJ @ TB"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'TB
               #:away           'NYJ
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772841
               #:name           "Las Vegas Raiders at Washington Commanders"
               #:short-name     "LV @ WSH"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'WSH
               #:away           'LV
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772838
               #:name           "Atlanta Falcons at Carolina Panthers"
               #:short-name     "ATL @ CAR"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'CAR
               #:away           'ATL
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772734
               #:name           "Houston Texans at Jacksonville Jaguars"
               #:short-name     "HOU @ JAX"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758474000)
               #:home           'JAX
               #:away           'HOU
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772735
               #:name           "Denver Broncos at Los Angeles Chargers"
               #:short-name     "DEN @ LAC"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758485100)
               #:home           'LAC
               #:away           'DEN
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772736
               #:name           "New Orleans Saints at Seattle Seahawks"
               #:short-name     "NO @ SEA"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758485100)
               #:home           'SEA
               #:away           'NO
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772844
               #:name           "Dallas Cowboys at Chicago Bears"
               #:short-name     "DAL @ CHI"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758486300)
               #:home           'CHI
               #:away           'DAL
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772843
               #:name           "Arizona Cardinals at San Francisco 49ers"
               #:short-name     "ARI @ SF"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758486300)
               #:home           'SF
               #:away           'ARI
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772920
               #:name           "Kansas City Chiefs at New York Giants"
               #:short-name     "KC @ NYG"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758500400)
               #:home           'NYG
               #:away           'KC
)
 2025 3)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772812
               #:name           "Detroit Lions at Baltimore Ravens"
               #:short-name     "DET @ BAL"
               #:year           2025
               #:week           2
               #:time           (secs->gametime 1758586500)
               #:home           'BAL
               #:away           'DET
)
 2025 3)

