(define-module (bad-cat nfldb data sched year-2025 week-01)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772510
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757031600)
               #:home           'PHI
               #:away           'DAL
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772714
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757116800)
               #:home           'LAC
               #:away           'KC
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772830
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'ATL
               #:away           'TB
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772829
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'CLE
               #:away           'CIN
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772719
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'IND
               #:away           'MIA
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772720
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'NE
               #:away           'LV
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772718
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'NO
               #:away           'ARI
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772721
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'NYJ
               #:away           'PIT
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772827
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'WSH
               #:away           'NYG
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772828
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757264400)
               #:home           'JAX
               #:away           'CAR
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772832
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757275500)
               #:home           'DEN
               #:away           'TEN
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772831
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757275500)
               #:home           'SEA
               #:away           'SF
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772722
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757276700)
               #:home           'GB
               #:away           'DET
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772723
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757276700)
               #:home           'LAR
               #:away           'HOU
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772918
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757290800)
               #:home           'BUF
               #:away           'BAL
)
 2025 1)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772810
               #:year           2025
               #:week           0
               #:time           (secs->gametime 1757376900)
               #:home           'CHI
               #:away           'MIN
)
 2025 1)

