(define-module (bad-cat nfldb data sched year-2025 week-14)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772947
               #:name           "Dallas Cowboys at Detroit Lions"
               #:short-name     "DAL @ DET"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1764900900)
               #:home           'DET
               #:away           'DAL
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772900
               #:name           "Seattle Seahawks at Atlanta Falcons"
               #:short-name     "SEA @ ATL"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'ATL
               #:away           'SEA
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772898
               #:name           "Tennessee Titans at Cleveland Browns"
               #:short-name     "TEN @ CLE"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'CLE
               #:away           'TEN
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772897
               #:name           "Chicago Bears at Green Bay Packers"
               #:short-name     "CHI @ GB"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'GB
               #:away           'CHI
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772899
               #:name           "Washington Commanders at Minnesota Vikings"
               #:short-name     "WSH @ MIN"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'MIN
               #:away           'WSH
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772790
               #:name           "Miami Dolphins at New York Jets"
               #:short-name     "MIA @ NYJ"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'NYJ
               #:away           'MIA
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772792
               #:name           "New Orleans Saints at Tampa Bay Buccaneers"
               #:short-name     "NO @ TB"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'TB
               #:away           'NO
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772793
               #:name           "Indianapolis Colts at Jacksonville Jaguars"
               #:short-name     "IND @ JAX"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'JAX
               #:away           'IND
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772791
               #:name           "Pittsburgh Steelers at Baltimore Ravens"
               #:short-name     "PIT @ BAL"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765134000)
               #:home           'BAL
               #:away           'PIT
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772794
               #:name           "Denver Broncos at Las Vegas Raiders"
               #:short-name     "DEN @ LV"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765145100)
               #:home           'LV
               #:away           'DEN
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772902
               #:name           "Cincinnati Bengals at Buffalo Bills"
               #:short-name     "CIN @ BUF"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765146300)
               #:home           'BUF
               #:away           'CIN
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772901
               #:name           "Los Angeles Rams at Arizona Cardinals"
               #:short-name     "LAR @ ARI"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765146300)
               #:home           'ARI
               #:away           'LAR
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772932
               #:name           "Houston Texans at Kansas City Chiefs"
               #:short-name     "HOU @ KC"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765160400)
               #:home           'KC
               #:away           'HOU
)
 2025 14)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772822
               #:name           "Philadelphia Eagles at Los Angeles Chargers"
               #:short-name     "PHI @ LAC"
               #:year           2025
               #:week           13
               #:time           (secs->gametime 1765246500)
               #:home           'LAC
               #:away           'PHI
)
 2025 14)

