(define-module (bad-cat nfldb data sched year-2025 week-10)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772944
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762481700)
               #:home           'DEN
               #:away           'LV
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772636
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762702200)
               #:home           'IND
               #:away           'ATL
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772875
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762714800)
               #:home           'CHI
               #:away           'NYG
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772771
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762714800)
               #:home           'MIA
               #:away           'BUF
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772876
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762714800)
               #:home           'MIN
               #:away           'BAL
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772769
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762714800)
               #:home           'NYJ
               #:away           'CLE
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772772
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762714800)
               #:home           'TB
               #:away           'NE
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772877
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762714800)
               #:home           'CAR
               #:away           'NO
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772770
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762714800)
               #:home           'HOU
               #:away           'JAX
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772773
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762725900)
               #:home           'SEA
               #:away           'ARI
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772879
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762727100)
               #:home           'SF
               #:away           'LAR
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772878
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762727100)
               #:home           'WSH
               #:away           'DET
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772927
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762741200)
               #:home           'LAC
               #:away           'PIT
)
 2025 10)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772630
               #:year           2025
               #:week           9
               #:time           (secs->gametime 1762827300)
               #:home           'GB
               #:away           'PHI
)
 2025 10)

