(define-module (bad-cat nfldb data sched year-2025 week-11)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772945
               #:name           "New York Jets at New England Patriots"
               #:short-name     "NYJ @ NE"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763086500)
               #:home           'NE
               #:away           'NYJ
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772631
               #:name           "Washington Commanders at Miami Dolphins"
               #:short-name     "WSH VS MIA"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763307000)
               #:home           'MIA
               #:away           'WSH
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772882
               #:name           "Carolina Panthers at Atlanta Falcons"
               #:short-name     "CAR @ ATL"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'ATL
               #:away           'CAR
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772776
               #:name           "Tampa Bay Buccaneers at Buffalo Bills"
               #:short-name     "TB @ BUF"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'BUF
               #:away           'TB
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772881
               #:name           "Houston Texans at Tennessee Titans"
               #:short-name     "HOU @ TEN"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'TEN
               #:away           'HOU
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772880
               #:name           "Chicago Bears at Minnesota Vikings"
               #:short-name     "CHI @ MIN"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'MIN
               #:away           'CHI
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772883
               #:name           "Green Bay Packers at New York Giants"
               #:short-name     "GB @ NYG"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'NYG
               #:away           'GB
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772774
               #:name           "Cincinnati Bengals at Pittsburgh Steelers"
               #:short-name     "CIN @ PIT"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'PIT
               #:away           'CIN
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772775
               #:name           "Los Angeles Chargers at Jacksonville Jaguars"
               #:short-name     "LAC @ JAX"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'JAX
               #:away           'LAC
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772884
               #:name           "Seattle Seahawks at Los Angeles Rams"
               #:short-name     "SEA @ LAR"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763330700)
               #:home           'LAR
               #:away           'SEA
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772885
               #:name           "San Francisco 49ers at Arizona Cardinals"
               #:short-name     "SF @ ARI"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763330700)
               #:home           'ARI
               #:away           'SF
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772777
               #:name           "Baltimore Ravens at Cleveland Browns"
               #:short-name     "BAL @ CLE"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763331900)
               #:home           'CLE
               #:away           'BAL
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772778
               #:name           "Kansas City Chiefs at Denver Broncos"
               #:short-name     "KC @ DEN"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763331900)
               #:home           'DEN
               #:away           'KC
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772928
               #:name           "Detroit Lions at Philadelphia Eagles"
               #:short-name     "DET @ PHI"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763346000)
               #:home           'PHI
               #:away           'DET
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772819
               #:name           "Dallas Cowboys at Las Vegas Raiders"
               #:short-name     "DAL @ LV"
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763432100)
               #:home           'LV
               #:away           'DAL
)
 2025 11)

