(define-module (bad-cat nfldb data sched year-2025 week-15)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772948
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765505700)
               #:home           'TB
               #:away           'ATL
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772904
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'CHI
               #:away           'CLE
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772796
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'CIN
               #:away           'BAL
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772798
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'KC
               #:away           'LAC
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772795
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'NE
               #:away           'BUF
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772905
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'NYG
               #:away           'WSH
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772906
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'PHI
               #:away           'LV
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772797
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'JAX
               #:away           'NYJ
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772903
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765738800)
               #:home           'HOU
               #:away           'ARI
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772800
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'DEN
               #:away           'GB
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772909
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'LAR
               #:away           'DET
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772908
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'NO
               #:away           'CAR
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772907
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'SF
               #:away           'TEN
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772799
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765751100)
               #:home           'SEA
               #:away           'IND
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772933
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765765200)
               #:home           'DAL
               #:away           'MIN
)
 2025 15)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772823
               #:year           2025
               #:week           14
               #:time           (secs->gametime 1765851300)
               #:home           'PIT
               #:away           'MIA
)
 2025 15)

