(define-module (bad-cat nfldb data sched year-2025 week-04)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772938
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1758845700)
               #:home           'ARI
               #:away           'SEA
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772632
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759066200)
               #:home           'PIT
               #:away           'MIN
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772739
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'ATL
               #:away           'WSH
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772740
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'BUF
               #:away           'NO
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772846
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'DET
               #:away           'CLE
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772847
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'NE
               #:away           'CAR
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772737
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'NYG
               #:away           'LAC
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772845
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'TB
               #:away           'PHI
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772738
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'HOU
               #:away           'TEN
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772849
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759089900)
               #:home           'LAR
               #:away           'IND
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772848
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759089900)
               #:home           'SF
               #:away           'JAX
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772741
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759091100)
               #:home           'KC
               #:away           'BAL
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772742
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759091100)
               #:home           'LV
               #:away           'CHI
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772921
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759105200)
               #:home           'DAL
               #:away           'GB
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772813
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759187700)
               #:home           'MIA
               #:away           'NYJ
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772716
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759191300)
               #:home           'DEN
               #:away           'CIN
)
 2025 4)

