(define-module (bad-cat nfldb data sched year-2025 week-17)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772710
               #:name           "Dallas Cowboys at Washington Commanders"
               #:short-name     "DAL @ WSH"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766689200)
               #:home           'WSH
               #:away           'DAL
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772711
               #:name           "Detroit Lions at Minnesota Vikings"
               #:short-name     "DET @ MIN"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766701800)
               #:home           'MIN
               #:away           'DET
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772622
               #:name           "Denver Broncos at Kansas City Chiefs"
               #:short-name     "DEN @ KC"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766715300)
               #:home           'KC
               #:away           'DEN
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772954
               #:name           "Arizona Cardinals at Cincinnati Bengals"
               #:short-name     "ARI @ CIN"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766815200)
               #:home           'CIN
               #:away           'ARI
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772953
               #:name           "Baltimore Ravens at Green Bay Packers"
               #:short-name     "BAL @ GB"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766815200)
               #:home           'GB
               #:away           'BAL
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772950
               #:name           "New York Giants at Las Vegas Raiders"
               #:short-name     "NYG @ LV"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766815200)
               #:home           'LV
               #:away           'NYG
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772951
               #:name           "Houston Texans at Los Angeles Chargers"
               #:short-name     "HOU @ LAC"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766815200)
               #:home           'LAC
               #:away           'HOU
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772952
               #:name           "Seattle Seahawks at Carolina Panthers"
               #:short-name     "SEA @ CAR"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766815200)
               #:home           'CAR
               #:away           'SEA
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772807
               #:name           "Pittsburgh Steelers at Cleveland Browns"
               #:short-name     "PIT @ CLE"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766948400)
               #:home           'CLE
               #:away           'PIT
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772809
               #:name           "New Orleans Saints at Tennessee Titans"
               #:short-name     "NO @ TEN"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766948400)
               #:home           'TEN
               #:away           'NO
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772915
               #:name           "Jacksonville Jaguars at Indianapolis Colts"
               #:short-name     "JAX @ IND"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766948400)
               #:home           'IND
               #:away           'JAX
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772916
               #:name           "Tampa Bay Buccaneers at Miami Dolphins"
               #:short-name     "TB @ MIA"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766948400)
               #:home           'MIA
               #:away           'TB
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772808
               #:name           "New England Patriots at New York Jets"
               #:short-name     "NE @ NYJ"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766948400)
               #:home           'NYJ
               #:away           'NE
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772917
               #:name           "Philadelphia Eagles at Buffalo Bills"
               #:short-name     "PHI @ BUF"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766960700)
               #:home           'BUF
               #:away           'PHI
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772935
               #:name           "Chicago Bears at San Francisco 49ers"
               #:short-name     "CHI @ SF"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1766974800)
               #:home           'SF
               #:away           'CHI
)
 2025 17)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772825
               #:name           "Los Angeles Rams at Atlanta Falcons"
               #:short-name     "LAR @ ATL"
               #:year           2025
               #:week           16
               #:time           (secs->gametime 1767060900)
               #:home           'ATL
               #:away           'LAR
)
 2025 17)

