(define-module (bad-cat nfldb data sched year-2025 week-11)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772945
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763086500)
               #:home           'NE
               #:away           'NYJ
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772631
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763307000)
               #:home           'MIA
               #:away           'WSH
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772882
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'ATL
               #:away           'CAR
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772776
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'BUF
               #:away           'TB
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772881
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'TEN
               #:away           'HOU
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772880
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'MIN
               #:away           'CHI
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772883
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'NYG
               #:away           'GB
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772774
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'PIT
               #:away           'CIN
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772775
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763319600)
               #:home           'JAX
               #:away           'LAC
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772884
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763330700)
               #:home           'LAR
               #:away           'SEA
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772885
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763330700)
               #:home           'ARI
               #:away           'SF
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772777
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763331900)
               #:home           'CLE
               #:away           'BAL
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772778
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763331900)
               #:home           'DEN
               #:away           'KC
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772928
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763346000)
               #:home           'PHI
               #:away           'DET
)
 2025 11)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772819
               #:year           2025
               #:week           10
               #:time           (secs->gametime 1763432100)
               #:home           'LV
               #:away           'DAL
)
 2025 11)

