(define-module (bad-cat nfldb data sched year-2025 week-09)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 14

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772943
               #:name           "Baltimore Ravens at Miami Dolphins"
               #:short-name     "BAL @ MIA"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1761869700)
               #:home           'MIA
               #:away           'BAL
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772765
               #:name           "Chicago Bears at Cincinnati Bengals"
               #:short-name     "CHI @ CIN"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'CIN
               #:away           'CHI
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772871
               #:name           "Minnesota Vikings at Detroit Lions"
               #:short-name     "MIN @ DET"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'DET
               #:away           'MIN
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772872
               #:name           "Carolina Panthers at Green Bay Packers"
               #:short-name     "CAR @ GB"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'GB
               #:away           'CAR
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772764
               #:name           "Los Angeles Chargers at Tennessee Titans"
               #:short-name     "LAC @ TEN"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'TEN
               #:away           'LAC
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772763
               #:name           "Atlanta Falcons at New England Patriots"
               #:short-name     "ATL @ NE"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'NE
               #:away           'ATL
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772767
               #:name           "San Francisco 49ers at New York Giants"
               #:short-name     "SF @ NYG"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'NYG
               #:away           'SF
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772766
               #:name           "Indianapolis Colts at Pittsburgh Steelers"
               #:short-name     "IND @ PIT"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'PIT
               #:away           'IND
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772870
               #:name           "Denver Broncos at Houston Texans"
               #:short-name     "DEN @ HOU"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762110000)
               #:home           'HOU
               #:away           'DEN
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772873
               #:name           "Jacksonville Jaguars at Las Vegas Raiders"
               #:short-name     "JAX @ LV"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762121100)
               #:home           'LV
               #:away           'JAX
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772874
               #:name           "New Orleans Saints at Los Angeles Rams"
               #:short-name     "NO @ LAR"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762121100)
               #:home           'LAR
               #:away           'NO
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772768
               #:name           "Kansas City Chiefs at Buffalo Bills"
               #:short-name     "KC @ BUF"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762122300)
               #:home           'BUF
               #:away           'KC
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772926
               #:name           "Seattle Seahawks at Washington Commanders"
               #:short-name     "SEA @ WSH"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762136400)
               #:home           'WSH
               #:away           'SEA
)
 2025 9)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772818
               #:name           "Arizona Cardinals at Dallas Cowboys"
               #:short-name     "ARI @ DAL"
               #:year           2025
               #:week           8
               #:time           (secs->gametime 1762222500)
               #:home           'DAL
               #:away           'ARI
)
 2025 9)

