(define-module (bad-cat nfldb data sched year-2025 week-07)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 15

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772941
               #:name           "Pittsburgh Steelers at Cincinnati Bengals"
               #:short-name     "PIT @ CIN"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760660100)
               #:home           'CIN
               #:away           'PIT
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772635
               #:name           "Los Angeles Rams at Jacksonville Jaguars"
               #:short-name     "LAR VS JAX"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760880600)
               #:home           'JAX
               #:away           'LAR
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772861
               #:name           "New Orleans Saints at Chicago Bears"
               #:short-name     "NO @ CHI"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760893200)
               #:home           'CHI
               #:away           'NO
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772754
               #:name           "Miami Dolphins at Cleveland Browns"
               #:short-name     "MIA @ CLE"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760893200)
               #:home           'CLE
               #:away           'MIA
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772755
               #:name           "New England Patriots at Tennessee Titans"
               #:short-name     "NE @ TEN"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760893200)
               #:home           'TEN
               #:away           'NE
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772753
               #:name           "Las Vegas Raiders at Kansas City Chiefs"
               #:short-name     "LV @ KC"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760893200)
               #:home           'KC
               #:away           'LV
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772862
               #:name           "Philadelphia Eagles at Minnesota Vikings"
               #:short-name     "PHI @ MIN"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760893200)
               #:home           'MIN
               #:away           'PHI
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772860
               #:name           "Carolina Panthers at New York Jets"
               #:short-name     "CAR @ NYJ"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760893200)
               #:home           'NYJ
               #:away           'CAR
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772757
               #:name           "New York Giants at Denver Broncos"
               #:short-name     "NYG @ DEN"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760904300)
               #:home           'DEN
               #:away           'NYG
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772756
               #:name           "Indianapolis Colts at Los Angeles Chargers"
               #:short-name     "IND @ LAC"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760904300)
               #:home           'LAC
               #:away           'IND
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772864
               #:name           "Washington Commanders at Dallas Cowboys"
               #:short-name     "WSH @ DAL"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760905500)
               #:home           'DAL
               #:away           'WSH
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772863
               #:name           "Green Bay Packers at Arizona Cardinals"
               #:short-name     "GB @ ARI"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760905500)
               #:home           'ARI
               #:away           'GB
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772924
               #:name           "Atlanta Falcons at San Francisco 49ers"
               #:short-name     "ATL @ SF"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1760919600)
               #:home           'SF
               #:away           'ATL
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772816
               #:name           "Tampa Bay Buccaneers at Detroit Lions"
               #:short-name     "TB @ DET"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1761001200)
               #:home           'DET
               #:away           'TB
)
 2025 7)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772826
               #:name           "Houston Texans at Seattle Seahawks"
               #:short-name     "HOU @ SEA"
               #:year           2025
               #:week           6
               #:time           (secs->gametime 1761012000)
               #:home           'SEA
               #:away           'HOU
)
 2025 7)

