(define-module (bad-cat nfldb data sched year-2025 week-04)
 ;; DO NOT EDIT! Generated by sandbox/espn.scm write-module-file
 ;; Just a hack for now to keep from having to download static data every time the script is loaded
 ;; Number of games: 16

 #:use-module (oop goops)
 #:use-module (bad-cat utils)
 #:use-module (bad-cat nfldb team)
 #:use-module (bad-cat nfldb game)
 #:use-module (bad-cat nfldb cache)
)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772938
               #:name           "Seattle Seahawks at Arizona Cardinals"
               #:short-name     "SEA @ ARI"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1758845700)
               #:home           'ARI
               #:away           'SEA
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772632
               #:name           "Minnesota Vikings at Pittsburgh Steelers"
               #:short-name     "MIN VS PIT"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759066200)
               #:home           'PIT
               #:away           'MIN
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772739
               #:name           "Washington Commanders at Atlanta Falcons"
               #:short-name     "WSH @ ATL"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'ATL
               #:away           'WSH
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772740
               #:name           "New Orleans Saints at Buffalo Bills"
               #:short-name     "NO @ BUF"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'BUF
               #:away           'NO
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772846
               #:name           "Cleveland Browns at Detroit Lions"
               #:short-name     "CLE @ DET"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'DET
               #:away           'CLE
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772847
               #:name           "Carolina Panthers at New England Patriots"
               #:short-name     "CAR @ NE"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'NE
               #:away           'CAR
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772737
               #:name           "Los Angeles Chargers at New York Giants"
               #:short-name     "LAC @ NYG"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'NYG
               #:away           'LAC
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772845
               #:name           "Philadelphia Eagles at Tampa Bay Buccaneers"
               #:short-name     "PHI @ TB"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'TB
               #:away           'PHI
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772738
               #:name           "Tennessee Titans at Houston Texans"
               #:short-name     "TEN @ HOU"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759078800)
               #:home           'HOU
               #:away           'TEN
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772849
               #:name           "Indianapolis Colts at Los Angeles Rams"
               #:short-name     "IND @ LAR"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759089900)
               #:home           'LAR
               #:away           'IND
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772848
               #:name           "Jacksonville Jaguars at San Francisco 49ers"
               #:short-name     "JAX @ SF"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759089900)
               #:home           'SF
               #:away           'JAX
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772741
               #:name           "Baltimore Ravens at Kansas City Chiefs"
               #:short-name     "BAL @ KC"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759091100)
               #:home           'KC
               #:away           'BAL
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772742
               #:name           "Chicago Bears at Las Vegas Raiders"
               #:short-name     "CHI @ LV"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759091100)
               #:home           'LV
               #:away           'CHI
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772921
               #:name           "Green Bay Packers at Dallas Cowboys"
               #:short-name     "GB @ DAL"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759105200)
               #:home           'DAL
               #:away           'GB
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772813
               #:name           "New York Jets at Miami Dolphins"
               #:short-name     "NYJ @ MIA"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759187700)
               #:home           'MIA
               #:away           'NYJ
)
 2025 4)


(cache-add-game-for-week (make-instance <nfl-game>
               #:id             401772716
               #:name           "Cincinnati Bengals at Denver Broncos"
               #:short-name     "CIN @ DEN"
               #:year           2025
               #:week           3
               #:time           (secs->gametime 1759191300)
               #:home           'DEN
               #:away           'CIN
)
 2025 4)

